// Airalo Country-Specific Affiliate Links Mapping
// This file contains the mapping from country names to their specific Airalo affiliate links

export interface AiraloAffiliateMapping {
  [countryKey: string]: string;
}

// Country name to Airalo affiliate link mapping
export const AIRALO_AFFILIATE_MAPPING: AiraloAffiliateMapping = {
  'afghanistan': 'https://www.airalo.com/it/afghanistan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'albania': 'https://www.airalo.com/it/albania-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'algeria': 'https://www.airalo.com/it/algeria-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'andorra': 'https://www.airalo.com/it/andorra-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'angola': 'https://www.airalo.com/it/angola-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'anguilla': 'https://www.airalo.com/it/anguilla-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'antigua-and-barbuda': 'https://www.airalo.com/it/antigua-and-barbuda-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'arabia-saudita': 'https://www.airalo.com/it/saudi-arabia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'argentina': 'https://www.airalo.com/it/argentina-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'armenia': 'https://www.airalo.com/it/armenia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'aruba': 'https://www.airalo.com/it/aruba-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'australia': 'https://www.airalo.com/it/australia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'austria': 'https://www.airalo.com/it/austria-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'azerbaigian': 'https://www.airalo.com/it/azerbaijan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bahamas': 'https://www.airalo.com/it/bahamas-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bahrain': 'https://www.airalo.com/it/bahrain-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bangladesh': 'https://www.airalo.com/it/bangladesh-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'barbados': 'https://www.airalo.com/it/barbados-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'belgio': 'https://www.airalo.com/it/belgium-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'belize': 'https://www.airalo.com/it/belize-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'benin': 'https://www.airalo.com/it/benin-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bermuda': 'https://www.airalo.com/it/bermuda-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bhutan': 'https://www.airalo.com/it/bhutan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bielorussia': 'https://www.airalo.com/it/belarus-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bolivia': 'https://www.airalo.com/it/bolivia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bosnia-ed-erzegovina': 'https://www.airalo.com/it/bosnia-and-herzegovina-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'botswana': 'https://www.airalo.com/it/botswana-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'brasile': 'https://www.airalo.com/it/brazil-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'brunei': 'https://www.airalo.com/it/brunei-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'bulgaria': 'https://www.airalo.com/it/bulgaria-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'burkina-faso': 'https://www.airalo.com/it/burkina-faso-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'burundi': 'https://www.airalo.com/it/burundi-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'cambogia': 'https://www.airalo.com/it/cambodia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'camerun': 'https://www.airalo.com/it/cameroon-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'canada': 'https://www.airalo.com/it/canada-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'capo-verde': 'https://www.airalo.com/it/cape-verde-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'repubblica-ceca': 'https://www.airalo.com/it/czech-republic-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'chad': 'https://www.airalo.com/it/chad-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'cile': 'https://www.airalo.com/it/chile-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'cina': 'https://www.airalo.com/it/china-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'hong-kong': 'https://www.airalo.com/it/hong-kong-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'cipro': 'https://www.airalo.com/it/cyprus-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'vaticano': 'https://www.airalo.com/it/vatican-city-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'colombia': 'https://www.airalo.com/it/colombia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'comore': 'https://www.airalo.com/it/comoros-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'congo-brazzaville': 'https://www.airalo.com/it/congo-brazzaville-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'congo-kinshasa': 'https://www.airalo.com/it/congo-kinshasa-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'corea-del-sud': 'https://www.airalo.com/it/south-korea-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'costa-rica': 'https://www.airalo.com/it/costa-rica-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'costa-d-avorio': 'https://www.airalo.com/it/ivory-coast-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'croazia': 'https://www.airalo.com/it/croatia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'cuba': 'https://www.airalo.com/it/cuba-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'curacao': 'https://www.airalo.com/it/curacao-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'danimarca': 'https://www.airalo.com/it/denmark-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'dominica': 'https://www.airalo.com/it/dominica-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'ecuador': 'https://www.airalo.com/it/ecuador-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'egitto': 'https://www.airalo.com/it/egypt-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'el-salvador': 'https://www.airalo.com/it/el-salvador-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'emirati-arabi-uniti': 'https://www.airalo.com/it/united-arab-emirates-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'estonia': 'https://www.airalo.com/it/estonia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'etiopia': 'https://www.airalo.com/it/ethiopia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'figi': 'https://www.airalo.com/it/fiji-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'filippine': 'https://www.airalo.com/it/philippines-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'finlandia': 'https://www.airalo.com/it/finland-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'francia': 'https://www.airalo.com/it/france-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'gabon': 'https://www.airalo.com/it/gabon-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'gambia': 'https://www.airalo.com/it/gambia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'georgia': 'https://www.airalo.com/it/georgia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'germania': 'https://www.airalo.com/it/germany-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'ghana': 'https://www.airalo.com/it/ghana-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'giamaica': 'https://www.airalo.com/it/jamaica-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'giappone': 'https://www.airalo.com/it/japan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'gibilterra': 'https://www.airalo.com/it/gibraltar-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'giordania': 'https://www.airalo.com/it/jordan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'grenada': 'https://www.airalo.com/it/grenada-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'grecia': 'https://www.airalo.com/it/greece-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'groenlandia': 'https://www.airalo.com/it/greenland-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guadalupa': 'https://www.airalo.com/it/guadeloupe-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guam': 'https://www.airalo.com/it/guam-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guatemala': 'https://www.airalo.com/it/guatemala-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guernsey': 'https://www.airalo.com/it/guernsey-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guyana-francese': 'https://www.airalo.com/it/french-guiana-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guinea': 'https://www.airalo.com/it/guinea-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guinea-bissau': 'https://www.airalo.com/it/guinea-bissau-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'guyana': 'https://www.airalo.com/it/guyana-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'haiti': 'https://www.airalo.com/it/haiti-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'honduras': 'https://www.airalo.com/it/honduras-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'india': 'https://www.airalo.com/it/india-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'indonesia': 'https://www.airalo.com/it/indonesia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'iran': 'https://www.airalo.com/it/iran-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'iraq': 'https://www.airalo.com/it/iraq-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'irlanda': 'https://www.airalo.com/it/ireland-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'islanda': 'https://www.airalo.com/it/iceland-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isola-di-man': 'https://www.airalo.com/it/isle-of-man-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isole-cayman': 'https://www.airalo.com/it/cayman-islands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isole-faroe': 'https://www.airalo.com/it/faroe-islands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isole-salomone': 'https://www.airalo.com/it/solomon-islands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isole-turks-e-caicos': 'https://www.airalo.com/it/turks-and-caicos-islands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isole-vergini-britanniche': 'https://www.airalo.com/it/british-virgin-islands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'isole-vergini-americane': 'https://www.airalo.com/it/us-virgin-islands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'israele': 'https://www.airalo.com/it/israel-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'italia': 'https://www.airalo.com/it/italy-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'kazakistan': 'https://www.airalo.com/it/kazakhstan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'kenya': 'https://www.airalo.com/it/kenya-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'kirghizistan': 'https://www.airalo.com/it/kyrgyzstan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'kiribati': 'https://www.airalo.com/it/kiribati-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'kosovo': 'https://www.airalo.com/it/kosovo-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'kuwait': 'https://www.airalo.com/it/kuwait-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'laos': 'https://www.airalo.com/it/laos-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'lesotho': 'https://www.airalo.com/it/lesotho-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'lettonia': 'https://www.airalo.com/it/latvia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'liberia': 'https://www.airalo.com/it/liberia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'liechtenstein': 'https://www.airalo.com/it/liechtenstein-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'lituania': 'https://www.airalo.com/it/lithuania-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'lussemburgo': 'https://www.airalo.com/it/luxembourg-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'macedonia-del-nord': 'https://www.airalo.com/it/north-macedonia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'madagascar': 'https://www.airalo.com/it/madagascar-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'malawi': 'https://www.airalo.com/it/malawi-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'malaysia': 'https://www.airalo.com/it/malaysia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'maldive': 'https://www.airalo.com/it/maldives-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'mali': 'https://www.airalo.com/it/mali-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'malta': 'https://www.airalo.com/it/malta-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'marocco': 'https://www.airalo.com/it/morocco-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'martinica': 'https://www.airalo.com/it/martinique-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'mauritania': 'https://www.airalo.com/it/mauritania-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'mauritius': 'https://www.airalo.com/it/mauritius-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'mayotte': 'https://www.airalo.com/it/mayotte-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'messico': 'https://www.airalo.com/it/mexico-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'moldavia': 'https://www.airalo.com/it/moldova-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'monaco': 'https://www.airalo.com/it/monaco-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'mongolia': 'https://www.airalo.com/it/mongolia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'montenegro': 'https://www.airalo.com/it/montenegro-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'montserrat': 'https://www.airalo.com/it/montserrat-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'mozambico': 'https://www.airalo.com/it/mozambique-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'namibia': 'https://www.airalo.com/it/namibia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'nauru': 'https://www.airalo.com/it/nauru-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'nepal': 'https://www.airalo.com/it/nepal-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'nicaragua': 'https://www.airalo.com/it/nicaragua-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'niger': 'https://www.airalo.com/it/niger-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'nigeria': 'https://www.airalo.com/it/nigeria-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'norvegia': 'https://www.airalo.com/it/norway-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'nuova-caledonia': 'https://www.airalo.com/it/new-caledonia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'nuova-zelanda': 'https://www.airalo.com/it/new-zealand-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'olanda': 'https://www.airalo.com/it/netherlands-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'oman': 'https://www.airalo.com/it/oman-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'pakistan': 'https://www.airalo.com/it/pakistan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'palau': 'https://www.airalo.com/it/palau-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'panama': 'https://www.airalo.com/it/panama-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'papua-nuova-guinea': 'https://www.airalo.com/it/papua-new-guinea-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'paraguay': 'https://www.airalo.com/it/paraguay-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'peru': 'https://www.airalo.com/it/peru-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'polinesia-francese': 'https://www.airalo.com/it/french-polynesia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'polonia': 'https://www.airalo.com/it/poland-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'portogallo': 'https://www.airalo.com/it/portugal-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'puerto-rico': 'https://www.airalo.com/it/puerto-rico-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'qatar': 'https://www.airalo.com/it/qatar-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'macao': 'https://www.airalo.com/it/macao-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'regno-unito': 'https://www.airalo.com/it/united-kingdom-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'repubblica-centrafricana': 'https://www.airalo.com/it/central-african-republic-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'repubblica-dominicana': 'https://www.airalo.com/it/dominican-republic-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'romania': 'https://www.airalo.com/it/romania-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'ruanda': 'https://www.airalo.com/it/rwanda-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'russia': 'https://www.airalo.com/it/russia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'saint-kitts-e-nevis': 'https://www.airalo.com/it/saint-kitts-and-nevis-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'saint-vincent-e-grenadine': 'https://www.airalo.com/it/saint-vincent-and-the-grenadines-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'samoa': 'https://www.airalo.com/it/samoa-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'samoa-americane': 'https://www.airalo.com/it/american-samoa-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'san-marino': 'https://www.airalo.com/it/san-marino-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'saint-martin': 'https://www.airalo.com/it/saint-martin-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'santa-lucia': 'https://www.airalo.com/it/saint-lucia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'senegal': 'https://www.airalo.com/it/senegal-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'serbia': 'https://www.airalo.com/it/serbia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'seychelles': 'https://www.airalo.com/it/seychelles-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'sierra-leone': 'https://www.airalo.com/it/sierra-leone-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'singapore': 'https://www.airalo.com/it/singapore-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'slovacchia': 'https://www.airalo.com/it/slovakia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'slovenia': 'https://www.airalo.com/it/slovenia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'spagna': 'https://www.airalo.com/it/spain-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'sri-lanka': 'https://www.airalo.com/it/sri-lanka-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'saint-barthelemy': 'https://www.airalo.com/it/saint-barthelemy-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'stati-uniti': 'https://www.airalo.com/it/united-states-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'sudafrica': 'https://www.airalo.com/it/south-africa-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'sudan': 'https://www.airalo.com/it/sudan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'sudan-del-sud': 'https://www.airalo.com/it/south-sudan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'suriname': 'https://www.airalo.com/it/suriname-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'svezia': 'https://www.airalo.com/it/sweden-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'svizzera': 'https://www.airalo.com/it/switzerland-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'eswatini': 'https://www.airalo.com/it/eswatini-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'tagikistan': 'https://www.airalo.com/it/tajikistan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'tailandia': 'https://www.airalo.com/it/thailand-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'taiwan': 'https://www.airalo.com/it/taiwan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'tanzania': 'https://www.airalo.com/it/tanzania-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'palestina': 'https://www.airalo.com/it/palestinian-territories-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'timor-est': 'https://www.airalo.com/it/east-timor-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'tonga': 'https://www.airalo.com/it/tonga-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'trinidad-e-tobago': 'https://www.airalo.com/it/trinidad-and-tobago-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'tunisia': 'https://www.airalo.com/it/tunisia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'turchia': 'https://www.airalo.com/it/turkey-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'ucraina': 'https://www.airalo.com/it/ukraine-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'uganda': 'https://www.airalo.com/it/uganda-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'ungheria': 'https://www.airalo.com/it/hungary-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'uruguay': 'https://www.airalo.com/it/uruguay-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'uzbekistan': 'https://www.airalo.com/it/uzbekistan-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'vanuatu': 'https://www.airalo.com/it/vanuatu-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'venezuela': 'https://www.airalo.com/it/venezuela-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'vietnam': 'https://www.airalo.com/it/vietnam-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'yemen': 'https://www.airalo.com/it/yemen-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'zambia': 'https://www.airalo.com/it/zambia-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido',
  'zimbabwe': 'https://www.airalo.com/it/zimbabwe-esim?irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=Andrea+Loperfido'
};

// Generic Airalo affiliate link (fallback)
export const AIRALO_GENERIC_AFFILIATE = 'https://finanza.me/airalo';

/**
 * Get the appropriate Airalo affiliate link for a given country
 * @param country - The country name (normalized to lowercase with hyphens)
 * @returns The specific affiliate link for the country, or the generic link if not found
 */
export function getAiraloAffiliateLink(country?: string): string {
  if (!country) {
    return AIRALO_GENERIC_AFFILIATE;
  }

  // Normalize country name: lowercase and replace spaces with hyphens
  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  
  return AIRALO_AFFILIATE_MAPPING[normalizedCountry] || AIRALO_GENERIC_AFFILIATE;
}

/**
 * Check if a country has a specific Airalo affiliate link
 * @param country - The country name
 * @returns True if a specific affiliate link exists, false otherwise
 */
export function hasSpecificAiraloLink(country?: string): boolean {
  if (!country) {
    return false;
  }

  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  return normalizedCountry in AIRALO_AFFILIATE_MAPPING;
}
