// GoMoWorld Country-Specific Affiliate Links Mapping
// This file contains the mapping from country names to their specific GoMoWorld affiliate links

export interface GoMoWorldAffiliateMapping {
  [countryKey: string]: string;
}

// Base parameters for all GoMoWorld links
const GOMOWORLD_BASE_PARAMS = '?sharedid=&irpid=3417596&irgwc=1&afsrc=1';

// Country name to GoMoWorld affiliate link mapping
export const GOMOWORLD_AFFILIATE_MAPPING: GoMoWorldAffiliateMapping = {
  'afghanistan': `https://www.gomoworld.com/en/destinations/Afghanistan${GOMOWORLD_BASE_PARAMS}`,
  'albania': `https://www.gomoworld.com/en/destinations/Albania${GOMOWORLD_BASE_PARAMS}`,
  'algeria': `https://www.gomoworld.com/en/destinations/Algeria${GOMOWORLD_BASE_PARAMS}`,
  'andorra': `https://www.gomoworld.com/en/destinations/Andorra${GOMOWORLD_BASE_PARAMS}`,
  'angola': `https://www.gomoworld.com/en/destinations/Angola${GOMOWORLD_BASE_PARAMS}`,
  'anguilla': `https://www.gomoworld.com/en/destinations/Anguilla${GOMOWORLD_BASE_PARAMS}`,
  'antigua-e-barbuda': `https://www.gomoworld.com/en/destinations/Antigua_and_Barbuda${GOMOWORLD_BASE_PARAMS}`,
  'arabia-saudita': `https://www.gomoworld.com/en/destinations/Saudi_Arabia${GOMOWORLD_BASE_PARAMS}`,
  'argentina': `https://www.gomoworld.com/en/destinations/Argentina${GOMOWORLD_BASE_PARAMS}`,
  'armenia': `https://www.gomoworld.com/en/destinations/Armenia${GOMOWORLD_BASE_PARAMS}`,
  'aruba': `https://www.gomoworld.com/en/destinations/Aruba${GOMOWORLD_BASE_PARAMS}`,
  'australia': `https://www.gomoworld.com/en/destinations/Australia${GOMOWORLD_BASE_PARAMS}`,
  'austria': `https://www.gomoworld.com/en/destinations/Austria${GOMOWORLD_BASE_PARAMS}`,
  'azerbaigian': `https://www.gomoworld.com/en/destinations/Azerbaijan${GOMOWORLD_BASE_PARAMS}`,
  'bahamas': `https://www.gomoworld.com/en/destinations/Bahamas${GOMOWORLD_BASE_PARAMS}`,
  'bahrain': `https://www.gomoworld.com/en/destinations/Bahrain${GOMOWORLD_BASE_PARAMS}`,
  'bangladesh': `https://www.gomoworld.com/en/destinations/Bangladesh${GOMOWORLD_BASE_PARAMS}`,
  'barbados': `https://www.gomoworld.com/en/destinations/Barbados${GOMOWORLD_BASE_PARAMS}`,
  'belgio': `https://www.gomoworld.com/en/destinations/Belgium${GOMOWORLD_BASE_PARAMS}`,
  'belize': `https://www.gomoworld.com/en/destinations/Belize${GOMOWORLD_BASE_PARAMS}`,
  'benin': `https://www.gomoworld.com/en/destinations/Benin${GOMOWORLD_BASE_PARAMS}`,
  'bermuda': `https://www.gomoworld.com/en/destinations/Bermuda${GOMOWORLD_BASE_PARAMS}`,
  'bhutan': `https://www.gomoworld.com/en/destinations/Bhutan${GOMOWORLD_BASE_PARAMS}`,
  'bielorussia': `https://www.gomoworld.com/en/destinations/Belarus${GOMOWORLD_BASE_PARAMS}`,
  'bolivia': `https://www.gomoworld.com/en/destinations/Bolivia${GOMOWORLD_BASE_PARAMS}`,
  'bosnia-ed-erzegovina': `https://www.gomoworld.com/en/destinations/Bosnia_and_Herzegovina${GOMOWORLD_BASE_PARAMS}`,
  'botswana': `https://www.gomoworld.com/en/destinations/Botswana${GOMOWORLD_BASE_PARAMS}`,
  'brasile': `https://www.gomoworld.com/en/destinations/Brazil${GOMOWORLD_BASE_PARAMS}`,
  'brunei': `https://www.gomoworld.com/en/destinations/Brunei${GOMOWORLD_BASE_PARAMS}`,
  'bulgaria': `https://www.gomoworld.com/en/destinations/Bulgaria${GOMOWORLD_BASE_PARAMS}`,
  'burkina-faso': `https://www.gomoworld.com/en/destinations/Burkina_Faso${GOMOWORLD_BASE_PARAMS}`,
  'burundi': `https://www.gomoworld.com/en/destinations/Burundi${GOMOWORLD_BASE_PARAMS}`,
  'cambogia': `https://www.gomoworld.com/en/destinations/Cambodia${GOMOWORLD_BASE_PARAMS}`,
  'camerun': `https://www.gomoworld.com/en/destinations/Cameroon${GOMOWORLD_BASE_PARAMS}`,
  'canada': `https://www.gomoworld.com/en/destinations/Canada${GOMOWORLD_BASE_PARAMS}`,
  'capo-verde': `https://www.gomoworld.com/en/destinations/Cape_Verde${GOMOWORLD_BASE_PARAMS}`,
  'repubblica-ceca': `https://www.gomoworld.com/en/destinations/Czech_Republic${GOMOWORLD_BASE_PARAMS}`,
  'chad': `https://www.gomoworld.com/en/destinations/Chad${GOMOWORLD_BASE_PARAMS}`,
  'cile': `https://www.gomoworld.com/en/destinations/Chile${GOMOWORLD_BASE_PARAMS}`,
  'cina': `https://www.gomoworld.com/en/destinations/China${GOMOWORLD_BASE_PARAMS}`,
  'hong-kong': `https://www.gomoworld.com/en/destinations/Hong_Kong${GOMOWORLD_BASE_PARAMS}`,
  'cipro': `https://www.gomoworld.com/en/destinations/Cyprus${GOMOWORLD_BASE_PARAMS}`,
  'vaticano': `https://www.gomoworld.com/en/destinations/Vatican_City${GOMOWORLD_BASE_PARAMS}`,
  'colombia': `https://www.gomoworld.com/en/destinations/Colombia${GOMOWORLD_BASE_PARAMS}`,
  'comore': `https://www.gomoworld.com/en/destinations/Comoros${GOMOWORLD_BASE_PARAMS}`,
  'congo-brazzaville': `https://www.gomoworld.com/en/destinations/Republic_of_the_Congo${GOMOWORLD_BASE_PARAMS}`,
  'congo-kinshasa': `https://www.gomoworld.com/en/destinations/Democratic_Republic_of_the_Congo${GOMOWORLD_BASE_PARAMS}`,
  'corea-del-sud': `https://www.gomoworld.com/en/destinations/South_Korea${GOMOWORLD_BASE_PARAMS}`,
  'costa-rica': `https://www.gomoworld.com/en/destinations/Costa_Rica${GOMOWORLD_BASE_PARAMS}`,
  'costa-d-avorio': `https://www.gomoworld.com/en/destinations/Ivory_Coast${GOMOWORLD_BASE_PARAMS}`,
  'croazia': `https://www.gomoworld.com/en/destinations/Croatia${GOMOWORLD_BASE_PARAMS}`,
  'cuba': `https://www.gomoworld.com/en/destinations/Cuba${GOMOWORLD_BASE_PARAMS}`,
  'curacao': `https://www.gomoworld.com/en/destinations/Curacao${GOMOWORLD_BASE_PARAMS}`,
  'danimarca': `https://www.gomoworld.com/en/destinations/Denmark${GOMOWORLD_BASE_PARAMS}`,
  'dominica': `https://www.gomoworld.com/en/destinations/Dominica${GOMOWORLD_BASE_PARAMS}`,
  'ecuador': `https://www.gomoworld.com/en/destinations/Ecuador${GOMOWORLD_BASE_PARAMS}`,
  'egitto': `https://www.gomoworld.com/en/destinations/Egypt${GOMOWORLD_BASE_PARAMS}`,
  'el-salvador': `https://www.gomoworld.com/en/destinations/El_Salvador${GOMOWORLD_BASE_PARAMS}`,
  'emirati-arabi-uniti': `https://www.gomoworld.com/en/destinations/United_Arab_Emirates${GOMOWORLD_BASE_PARAMS}`,
  'estonia': `https://www.gomoworld.com/en/destinations/Estonia${GOMOWORLD_BASE_PARAMS}`,
  'etiopia': `https://www.gomoworld.com/en/destinations/Ethiopia${GOMOWORLD_BASE_PARAMS}`,
  'figi': `https://www.gomoworld.com/en/destinations/Fiji${GOMOWORLD_BASE_PARAMS}`,
  'filippine': `https://www.gomoworld.com/en/destinations/Philippines${GOMOWORLD_BASE_PARAMS}`,
  'finlandia': `https://www.gomoworld.com/en/destinations/Finland${GOMOWORLD_BASE_PARAMS}`,
  'francia': `https://www.gomoworld.com/en/destinations/France${GOMOWORLD_BASE_PARAMS}`,
  'gabon': `https://www.gomoworld.com/en/destinations/Gabon${GOMOWORLD_BASE_PARAMS}`,
  'gambia': `https://www.gomoworld.com/en/destinations/Gambia${GOMOWORLD_BASE_PARAMS}`,
  'georgia': `https://www.gomoworld.com/en/destinations/Georgia${GOMOWORLD_BASE_PARAMS}`,
  'germania': `https://www.gomoworld.com/en/destinations/Germany${GOMOWORLD_BASE_PARAMS}`,
  'ghana': `https://www.gomoworld.com/en/destinations/Ghana${GOMOWORLD_BASE_PARAMS}`,
  'giamaica': `https://www.gomoworld.com/en/destinations/Jamaica${GOMOWORLD_BASE_PARAMS}`,
  'giappone': `https://www.gomoworld.com/en/destinations/Japan${GOMOWORLD_BASE_PARAMS}`,
  'gibilterra': `https://www.gomoworld.com/en/destinations/Gibraltar${GOMOWORLD_BASE_PARAMS}`,
  'giordania': `https://www.gomoworld.com/en/destinations/Jordan${GOMOWORLD_BASE_PARAMS}`,
  'grenada': `https://www.gomoworld.com/en/destinations/Grenada${GOMOWORLD_BASE_PARAMS}`,
  'grecia': `https://www.gomoworld.com/en/destinations/Greece${GOMOWORLD_BASE_PARAMS}`,
  'groenlandia': `https://www.gomoworld.com/en/destinations/Greenland${GOMOWORLD_BASE_PARAMS}`,
  'guadalupa': `https://www.gomoworld.com/en/destinations/Guadeloupe${GOMOWORLD_BASE_PARAMS}`,
  'guam': `https://www.gomoworld.com/en/destinations/Guam${GOMOWORLD_BASE_PARAMS}`,
  'guatemala': `https://www.gomoworld.com/en/destinations/Guatemala${GOMOWORLD_BASE_PARAMS}`,
  'guernsey': `https://www.gomoworld.com/en/destinations/Guernsey${GOMOWORLD_BASE_PARAMS}`,
  'guyana-francese': `https://www.gomoworld.com/en/destinations/French_Guiana${GOMOWORLD_BASE_PARAMS}`,
  'guinea': `https://www.gomoworld.com/en/destinations/Guinea${GOMOWORLD_BASE_PARAMS}`,
  'guinea-bissau': `https://www.gomoworld.com/en/destinations/Guinea_Bissau${GOMOWORLD_BASE_PARAMS}`,
  'guyana': `https://www.gomoworld.com/en/destinations/Guyana${GOMOWORLD_BASE_PARAMS}`,
  'haiti': `https://www.gomoworld.com/en/destinations/Haiti${GOMOWORLD_BASE_PARAMS}`,
  'honduras': `https://www.gomoworld.com/en/destinations/Honduras${GOMOWORLD_BASE_PARAMS}`,
  'india': `https://www.gomoworld.com/en/destinations/India${GOMOWORLD_BASE_PARAMS}`,
  'indonesia': `https://www.gomoworld.com/en/destinations/Indonesia${GOMOWORLD_BASE_PARAMS}`,
  'iran': `https://www.gomoworld.com/en/destinations/Iran${GOMOWORLD_BASE_PARAMS}`,
  'iraq': `https://www.gomoworld.com/en/destinations/Iraq${GOMOWORLD_BASE_PARAMS}`,
  'irlanda': `https://www.gomoworld.com/en/destinations/Ireland${GOMOWORLD_BASE_PARAMS}`,
  'islanda': `https://www.gomoworld.com/en/destinations/Iceland${GOMOWORLD_BASE_PARAMS}`,
  'isola-di-man': `https://www.gomoworld.com/en/destinations/Isle_of_Man${GOMOWORLD_BASE_PARAMS}`,
  'isole-cayman': `https://www.gomoworld.com/en/destinations/Cayman_Islands${GOMOWORLD_BASE_PARAMS}`,
  'isole-faroe': `https://www.gomoworld.com/en/destinations/Faroe_Islands${GOMOWORLD_BASE_PARAMS}`,
  'isole-salomone': `https://www.gomoworld.com/en/destinations/Solomon_Islands${GOMOWORLD_BASE_PARAMS}`,
  'isole-turks-e-caicos': `https://www.gomoworld.com/en/destinations/Turks_and_Caicos_Islands${GOMOWORLD_BASE_PARAMS}`,
  'isole-vergini-britanniche': `https://www.gomoworld.com/en/destinations/British_Virgin_Islands${GOMOWORLD_BASE_PARAMS}`,
  'isole-vergini-americane': `https://www.gomoworld.com/en/destinations/US_Virgin_Islands${GOMOWORLD_BASE_PARAMS}`,
  'israele': `https://www.gomoworld.com/en/destinations/Israel${GOMOWORLD_BASE_PARAMS}`,
  'italia': `https://www.gomoworld.com/en/destinations/Italy${GOMOWORLD_BASE_PARAMS}`,
  'kazakistan': `https://www.gomoworld.com/en/destinations/Kazakhstan${GOMOWORLD_BASE_PARAMS}`,
  'kenya': `https://www.gomoworld.com/en/destinations/Kenya${GOMOWORLD_BASE_PARAMS}`,
  'kirghizistan': `https://www.gomoworld.com/en/destinations/Kyrgyzstan${GOMOWORLD_BASE_PARAMS}`,
  'kiribati': `https://www.gomoworld.com/en/destinations/Kiribati${GOMOWORLD_BASE_PARAMS}`,
  'kosovo': `https://www.gomoworld.com/en/destinations/Kosovo${GOMOWORLD_BASE_PARAMS}`,
  'kuwait': `https://www.gomoworld.com/en/destinations/Kuwait${GOMOWORLD_BASE_PARAMS}`,
  'laos': `https://www.gomoworld.com/en/destinations/Laos${GOMOWORLD_BASE_PARAMS}`,
  'lesotho': `https://www.gomoworld.com/en/destinations/Lesotho${GOMOWORLD_BASE_PARAMS}`,
  'lettonia': `https://www.gomoworld.com/en/destinations/Latvia${GOMOWORLD_BASE_PARAMS}`,
  'liberia': `https://www.gomoworld.com/en/destinations/Liberia${GOMOWORLD_BASE_PARAMS}`,
  'liechtenstein': `https://www.gomoworld.com/en/destinations/Liechtenstein${GOMOWORLD_BASE_PARAMS}`,
  'lituania': `https://www.gomoworld.com/en/destinations/Lithuania${GOMOWORLD_BASE_PARAMS}`,
  'lussemburgo': `https://www.gomoworld.com/en/destinations/Luxembourg${GOMOWORLD_BASE_PARAMS}`,
  'macedonia-del-nord': `https://www.gomoworld.com/en/destinations/North_Macedonia${GOMOWORLD_BASE_PARAMS}`,
  'madagascar': `https://www.gomoworld.com/en/destinations/Madagascar${GOMOWORLD_BASE_PARAMS}`,
  'malawi': `https://www.gomoworld.com/en/destinations/Malawi${GOMOWORLD_BASE_PARAMS}`,
  'malaysia': `https://www.gomoworld.com/en/destinations/Malaysia${GOMOWORLD_BASE_PARAMS}`,
  'maldive': `https://www.gomoworld.com/en/destinations/Maldives${GOMOWORLD_BASE_PARAMS}`,
  'mali': `https://www.gomoworld.com/en/destinations/Mali${GOMOWORLD_BASE_PARAMS}`,
  'malta': `https://www.gomoworld.com/en/destinations/Malta${GOMOWORLD_BASE_PARAMS}`,
  'marocco': `https://www.gomoworld.com/en/destinations/Morocco${GOMOWORLD_BASE_PARAMS}`,
  'martinica': `https://www.gomoworld.com/en/destinations/Martinique${GOMOWORLD_BASE_PARAMS}`,
  'mauritania': `https://www.gomoworld.com/en/destinations/Mauritania${GOMOWORLD_BASE_PARAMS}`,
  'mauritius': `https://www.gomoworld.com/en/destinations/Mauritius${GOMOWORLD_BASE_PARAMS}`,
  'mayotte': `https://www.gomoworld.com/en/destinations/Mayotte${GOMOWORLD_BASE_PARAMS}`,
  'messico': `https://www.gomoworld.com/en/destinations/Mexico${GOMOWORLD_BASE_PARAMS}`,
  'moldavia': `https://www.gomoworld.com/en/destinations/Moldova${GOMOWORLD_BASE_PARAMS}`,
  'monaco': `https://www.gomoworld.com/en/destinations/Monaco${GOMOWORLD_BASE_PARAMS}`,
  'mongolia': `https://www.gomoworld.com/en/destinations/Mongolia${GOMOWORLD_BASE_PARAMS}`,
  'montenegro': `https://www.gomoworld.com/en/destinations/Montenegro${GOMOWORLD_BASE_PARAMS}`,
  'montserrat': `https://www.gomoworld.com/en/destinations/Montserrat${GOMOWORLD_BASE_PARAMS}`,
  'mozambico': `https://www.gomoworld.com/en/destinations/Mozambique${GOMOWORLD_BASE_PARAMS}`,
  'namibia': `https://www.gomoworld.com/en/destinations/Namibia${GOMOWORLD_BASE_PARAMS}`,
  'nauru': `https://www.gomoworld.com/en/destinations/Nauru${GOMOWORLD_BASE_PARAMS}`,
  'nepal': `https://www.gomoworld.com/en/destinations/Nepal${GOMOWORLD_BASE_PARAMS}`,
  'nicaragua': `https://www.gomoworld.com/en/destinations/Nicaragua${GOMOWORLD_BASE_PARAMS}`,
  'niger': `https://www.gomoworld.com/en/destinations/Niger${GOMOWORLD_BASE_PARAMS}`,
  'nigeria': `https://www.gomoworld.com/en/destinations/Nigeria${GOMOWORLD_BASE_PARAMS}`,
  'norvegia': `https://www.gomoworld.com/en/destinations/Norway${GOMOWORLD_BASE_PARAMS}`,
  'nuova-caledonia': `https://www.gomoworld.com/en/destinations/New_Caledonia${GOMOWORLD_BASE_PARAMS}`,
  'nuova-zelanda': `https://www.gomoworld.com/en/destinations/New_Zealand${GOMOWORLD_BASE_PARAMS}`,
  'olanda': `https://www.gomoworld.com/en/destinations/Netherlands${GOMOWORLD_BASE_PARAMS}`,
  'oman': `https://www.gomoworld.com/en/destinations/Oman${GOMOWORLD_BASE_PARAMS}`,
  'pakistan': `https://www.gomoworld.com/en/destinations/Pakistan${GOMOWORLD_BASE_PARAMS}`,
  'palau': `https://www.gomoworld.com/en/destinations/Palau${GOMOWORLD_BASE_PARAMS}`,
  'panama': `https://www.gomoworld.com/en/destinations/Panama${GOMOWORLD_BASE_PARAMS}`,
  'papua-nuova-guinea': `https://www.gomoworld.com/en/destinations/Papua_New_Guinea${GOMOWORLD_BASE_PARAMS}`,
  'paraguay': `https://www.gomoworld.com/en/destinations/Paraguay${GOMOWORLD_BASE_PARAMS}`,
  'peru': `https://www.gomoworld.com/en/destinations/Peru${GOMOWORLD_BASE_PARAMS}`,
  'polinesia-francese': `https://www.gomoworld.com/en/destinations/French_Polynesia${GOMOWORLD_BASE_PARAMS}`,
  'polonia': `https://www.gomoworld.com/en/destinations/Poland${GOMOWORLD_BASE_PARAMS}`,
  'portogallo': `https://www.gomoworld.com/en/destinations/Portugal${GOMOWORLD_BASE_PARAMS}`,
  'puerto-rico': `https://www.gomoworld.com/en/destinations/Puerto_Rico${GOMOWORLD_BASE_PARAMS}`,
  'qatar': `https://www.gomoworld.com/en/destinations/Qatar${GOMOWORLD_BASE_PARAMS}`,
  'macao': `https://www.gomoworld.com/en/destinations/Macao${GOMOWORLD_BASE_PARAMS}`,
  'regno-unito': `https://www.gomoworld.com/en/destinations/United_Kingdom${GOMOWORLD_BASE_PARAMS}`,
  'repubblica-centrafricana': `https://www.gomoworld.com/en/destinations/Central_African_Republic${GOMOWORLD_BASE_PARAMS}`,
  'repubblica-dominicana': `https://www.gomoworld.com/en/destinations/Dominican_Republic${GOMOWORLD_BASE_PARAMS}`,
  'romania': `https://www.gomoworld.com/en/destinations/Romania${GOMOWORLD_BASE_PARAMS}`,
  'ruanda': `https://www.gomoworld.com/en/destinations/Rwanda${GOMOWORLD_BASE_PARAMS}`,
  'russia': `https://www.gomoworld.com/en/destinations/Russia${GOMOWORLD_BASE_PARAMS}`,
  'saint-kitts-e-nevis': `https://www.gomoworld.com/en/destinations/Saint_Kitts_and_Nevis${GOMOWORLD_BASE_PARAMS}`,
  'saint-vincent-e-grenadine': `https://www.gomoworld.com/en/destinations/Saint_Vincent_and_the_Grenadines${GOMOWORLD_BASE_PARAMS}`,
  'samoa': `https://www.gomoworld.com/en/destinations/Samoa${GOMOWORLD_BASE_PARAMS}`,
  'samoa-americane': `https://www.gomoworld.com/en/destinations/American_Samoa${GOMOWORLD_BASE_PARAMS}`,
  'san-marino': `https://www.gomoworld.com/en/destinations/San_Marino${GOMOWORLD_BASE_PARAMS}`,
  'saint-martin': `https://www.gomoworld.com/en/destinations/Saint_Martin${GOMOWORLD_BASE_PARAMS}`,
  'santa-lucia': `https://www.gomoworld.com/en/destinations/Saint_Lucia${GOMOWORLD_BASE_PARAMS}`,
  'senegal': `https://www.gomoworld.com/en/destinations/Senegal${GOMOWORLD_BASE_PARAMS}`,
  'serbia': `https://www.gomoworld.com/en/destinations/Serbia${GOMOWORLD_BASE_PARAMS}`,
  'seychelles': `https://www.gomoworld.com/en/destinations/Seychelles${GOMOWORLD_BASE_PARAMS}`,
  'sierra-leone': `https://www.gomoworld.com/en/destinations/Sierra_Leone${GOMOWORLD_BASE_PARAMS}`,
  'singapore': `https://www.gomoworld.com/en/destinations/Singapore${GOMOWORLD_BASE_PARAMS}`,
  'slovacchia': `https://www.gomoworld.com/en/destinations/Slovakia${GOMOWORLD_BASE_PARAMS}`,
  'slovenia': `https://www.gomoworld.com/en/destinations/Slovenia${GOMOWORLD_BASE_PARAMS}`,
  'spagna': `https://www.gomoworld.com/en/destinations/Spain${GOMOWORLD_BASE_PARAMS}`,
  'sri-lanka': `https://www.gomoworld.com/en/destinations/Sri_Lanka${GOMOWORLD_BASE_PARAMS}`,
  'saint-barthelemy': `https://www.gomoworld.com/en/destinations/Saint_Barthelemy${GOMOWORLD_BASE_PARAMS}`,
  'stati-uniti': `https://www.gomoworld.com/en/destinations/United_States${GOMOWORLD_BASE_PARAMS}`,
  'sudafrica': `https://www.gomoworld.com/en/destinations/South_Africa${GOMOWORLD_BASE_PARAMS}`,
  'sudan': `https://www.gomoworld.com/en/destinations/Sudan${GOMOWORLD_BASE_PARAMS}`,
  'sudan-del-sud': `https://www.gomoworld.com/en/destinations/South_Sudan${GOMOWORLD_BASE_PARAMS}`,
  'suriname': `https://www.gomoworld.com/en/destinations/Suriname${GOMOWORLD_BASE_PARAMS}`,
  'svezia': `https://www.gomoworld.com/en/destinations/Sweden${GOMOWORLD_BASE_PARAMS}`,
  'svizzera': `https://www.gomoworld.com/en/destinations/Switzerland${GOMOWORLD_BASE_PARAMS}`,
  'eswatini': `https://www.gomoworld.com/en/destinations/Eswatini${GOMOWORLD_BASE_PARAMS}`,
  'tagikistan': `https://www.gomoworld.com/en/destinations/Tajikistan${GOMOWORLD_BASE_PARAMS}`,
  'tailandia': `https://www.gomoworld.com/en/destinations/Thailand${GOMOWORLD_BASE_PARAMS}`,
  'taiwan': `https://www.gomoworld.com/en/destinations/Taiwan${GOMOWORLD_BASE_PARAMS}`,
  'tanzania': `https://www.gomoworld.com/en/destinations/Tanzania${GOMOWORLD_BASE_PARAMS}`,
  'palestina': `https://www.gomoworld.com/en/destinations/Palestine${GOMOWORLD_BASE_PARAMS}`,
  'timor-est': `https://www.gomoworld.com/en/destinations/Timor_Leste${GOMOWORLD_BASE_PARAMS}`,
  'tonga': `https://www.gomoworld.com/en/destinations/Tonga${GOMOWORLD_BASE_PARAMS}`,
  'trinidad-e-tobago': `https://www.gomoworld.com/en/destinations/Trinidad_and_Tobago${GOMOWORLD_BASE_PARAMS}`,
  'tunisia': `https://www.gomoworld.com/en/destinations/Tunisia${GOMOWORLD_BASE_PARAMS}`,
  'turchia': `https://www.gomoworld.com/en/destinations/Turkey${GOMOWORLD_BASE_PARAMS}`,
  'ucraina': `https://www.gomoworld.com/en/destinations/Ukraine${GOMOWORLD_BASE_PARAMS}`,
  'uganda': `https://www.gomoworld.com/en/destinations/Uganda${GOMOWORLD_BASE_PARAMS}`,
  'ungheria': `https://www.gomoworld.com/en/destinations/Hungary${GOMOWORLD_BASE_PARAMS}`,
  'uruguay': `https://www.gomoworld.com/en/destinations/Uruguay${GOMOWORLD_BASE_PARAMS}`,
  'uzbekistan': `https://www.gomoworld.com/en/destinations/Uzbekistan${GOMOWORLD_BASE_PARAMS}`,
  'vanuatu': `https://www.gomoworld.com/en/destinations/Vanuatu${GOMOWORLD_BASE_PARAMS}`,
  'venezuela': `https://www.gomoworld.com/en/destinations/Venezuela${GOMOWORLD_BASE_PARAMS}`,
  'vietnam': `https://www.gomoworld.com/en/destinations/Vietnam${GOMOWORLD_BASE_PARAMS}`,
  'yemen': `https://www.gomoworld.com/en/destinations/Yemen${GOMOWORLD_BASE_PARAMS}`,
  'zambia': `https://www.gomoworld.com/en/destinations/Zambia${GOMOWORLD_BASE_PARAMS}`,
  'zimbabwe': `https://www.gomoworld.com/en/destinations/Zimbabwe${GOMOWORLD_BASE_PARAMS}`
};

// Generic GoMoWorld affiliate link (fallback)
export const GOMOWORLD_GENERIC_AFFILIATE = 'https://finanza.me/gomoworld';

/**
 * Get the appropriate GoMoWorld affiliate link for a given country
 * @param country - The country name (normalized to lowercase with hyphens)
 * @returns The specific affiliate link for the country, or the generic link if not found
 */
export function getGoMoWorldAffiliateLink(country?: string): string {
  if (!country) {
    return GOMOWORLD_GENERIC_AFFILIATE;
  }

  // Normalize country name: lowercase and replace spaces with hyphens
  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  
  return GOMOWORLD_AFFILIATE_MAPPING[normalizedCountry] || GOMOWORLD_GENERIC_AFFILIATE;
}

/**
 * Check if a country has a specific GoMoWorld affiliate link
 * @param country - The country name
 * @returns True if a specific affiliate link exists, false otherwise
 */
export function hasSpecificGoMoWorldLink(country?: string): boolean {
  if (!country) {
    return false;
  }

  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  return normalizedCountry in GOMOWORLD_AFFILIATE_MAPPING;
}
