// Nomad Country-Specific Affiliate Links Mapping
// This file contains the mapping from country names to their specific Nomad affiliate links

export interface NomadAffiliateMapping {
  [countryKey: string]: string;
}

// Base parameters for all Nomad links
const NOMAD_BASE_PARAMS = '?sharedid=&irpid=3417596&irgwc=1&afsrc=1';

// Country name to Nomad affiliate link mapping
export const NOMAD_AFFILIATE_MAPPING: NomadAffiliateMapping = {
  'afghanistan': `https://www.getnomad.app/afghanistan-eSIM${NOMAD_BASE_PARAMS}`,
  'albania': `https://www.getnomad.app/albania-eSIM${NOMAD_BASE_PARAMS}`,
  'algeria': `https://www.getnomad.app/algeria-eSIM${NOMAD_BASE_PARAMS}`,
  'andorra': `https://www.getnomad.app/andorra-eSIM${NOMAD_BASE_PARAMS}`,
  'angola': `https://www.getnomad.app/angola-eSIM${NOMAD_BASE_PARAMS}`,
  'anguilla': `https://www.getnomad.app/anguilla-eSIM${NOMAD_BASE_PARAMS}`,
  'antigua-e-barbuda': `https://www.getnomad.app/antigua-and-barbuda-eSIM${NOMAD_BASE_PARAMS}`,
  'arabia-saudita': `https://www.getnomad.app/saudi-arabia-eSIM${NOMAD_BASE_PARAMS}`,
  'argentina': `https://www.getnomad.app/argentina-eSIM${NOMAD_BASE_PARAMS}`,
  'armenia': `https://www.getnomad.app/armenia-eSIM${NOMAD_BASE_PARAMS}`,
  'aruba': `https://www.getnomad.app/aruba-eSIM${NOMAD_BASE_PARAMS}`,
  'australia': `https://www.getnomad.app/australia-eSIM${NOMAD_BASE_PARAMS}`,
  'austria': `https://www.getnomad.app/austria-eSIM${NOMAD_BASE_PARAMS}`,
  'azerbaigian': `https://www.getnomad.app/azerbaijan-eSIM${NOMAD_BASE_PARAMS}`,
  'bahamas': `https://www.getnomad.app/bahamas-eSIM${NOMAD_BASE_PARAMS}`,
  'bahrain': `https://www.getnomad.app/bahrain-eSIM${NOMAD_BASE_PARAMS}`,
  'bangladesh': `https://www.getnomad.app/bangladesh-eSIM${NOMAD_BASE_PARAMS}`,
  'barbados': `https://www.getnomad.app/barbados-eSIM${NOMAD_BASE_PARAMS}`,
  'belgio': `https://www.getnomad.app/belgium-eSIM${NOMAD_BASE_PARAMS}`,
  'belize': `https://www.getnomad.app/belize-eSIM${NOMAD_BASE_PARAMS}`,
  'benin': `https://www.getnomad.app/benin-eSIM${NOMAD_BASE_PARAMS}`,
  'bermuda': `https://www.getnomad.app/bermuda-eSIM${NOMAD_BASE_PARAMS}`,
  'bhutan': `https://www.getnomad.app/bhutan-eSIM${NOMAD_BASE_PARAMS}`,
  'bielorussia': `https://www.getnomad.app/belarus-eSIM${NOMAD_BASE_PARAMS}`,
  'bolivia': `https://www.getnomad.app/bolivia-eSIM${NOMAD_BASE_PARAMS}`,
  'bosnia-ed-erzegovina': `https://www.getnomad.app/bosnia-and-herzegovina-eSIM${NOMAD_BASE_PARAMS}`,
  'botswana': `https://www.getnomad.app/botswana-eSIM${NOMAD_BASE_PARAMS}`,
  'brasile': `https://www.getnomad.app/brazil-eSIM${NOMAD_BASE_PARAMS}`,
  'brunei': `https://www.getnomad.app/brunei-eSIM${NOMAD_BASE_PARAMS}`,
  'bulgaria': `https://www.getnomad.app/bulgaria-eSIM${NOMAD_BASE_PARAMS}`,
  'burkina-faso': `https://www.getnomad.app/burkina-faso-eSIM${NOMAD_BASE_PARAMS}`,
  'burundi': `https://www.getnomad.app/burundi-eSIM${NOMAD_BASE_PARAMS}`,
  'cambogia': `https://www.getnomad.app/cambodia-eSIM${NOMAD_BASE_PARAMS}`,
  'camerun': `https://www.getnomad.app/cameroon-eSIM${NOMAD_BASE_PARAMS}`,
  'canada': `https://www.getnomad.app/canada-eSIM${NOMAD_BASE_PARAMS}`,
  'capo-verde': `https://www.getnomad.app/cape-verde-eSIM${NOMAD_BASE_PARAMS}`,
  'repubblica-ceca': `https://www.getnomad.app/czech-republic-eSIM${NOMAD_BASE_PARAMS}`,
  'chad': `https://www.getnomad.app/chad-eSIM${NOMAD_BASE_PARAMS}`,
  'cile': `https://www.getnomad.app/chile-eSIM${NOMAD_BASE_PARAMS}`,
  'cina': `https://www.getnomad.app/china-eSIM${NOMAD_BASE_PARAMS}`,
  'hong-kong': `https://www.getnomad.app/hong-kong-eSIM${NOMAD_BASE_PARAMS}`,
  'cipro': `https://www.getnomad.app/cyprus-eSIM${NOMAD_BASE_PARAMS}`,
  'vaticano': `https://www.getnomad.app/vatican-city-eSIM${NOMAD_BASE_PARAMS}`,
  'colombia': `https://www.getnomad.app/colombia-eSIM${NOMAD_BASE_PARAMS}`,
  'comore': `https://www.getnomad.app/comoros-eSIM${NOMAD_BASE_PARAMS}`,
  'congo-brazzaville': `https://www.getnomad.app/republic-of-congo-eSIM${NOMAD_BASE_PARAMS}`,
  'congo-kinshasa': `https://www.getnomad.app/democratic-republic-of-congo-eSIM${NOMAD_BASE_PARAMS}`,
  'corea-del-sud': `https://www.getnomad.app/south-korea-eSIM${NOMAD_BASE_PARAMS}`,
  'costa-rica': `https://www.getnomad.app/costa-rica-eSIM${NOMAD_BASE_PARAMS}`,
  'costa-d-avorio': `https://www.getnomad.app/cote-d-ivoire-eSIM${NOMAD_BASE_PARAMS}`,
  'croazia': `https://www.getnomad.app/croatia-eSIM${NOMAD_BASE_PARAMS}`,
  'cuba': `https://www.getnomad.app/cuba-eSIM${NOMAD_BASE_PARAMS}`,
  'curacao': `https://www.getnomad.app/curacao-eSIM${NOMAD_BASE_PARAMS}`,
  'danimarca': `https://www.getnomad.app/denmark-eSIM${NOMAD_BASE_PARAMS}`,
  'dominica': `https://www.getnomad.app/dominica-eSIM${NOMAD_BASE_PARAMS}`,
  'ecuador': `https://www.getnomad.app/ecuador-eSIM${NOMAD_BASE_PARAMS}`,
  'egitto': `https://www.getnomad.app/egypt-eSIM${NOMAD_BASE_PARAMS}`,
  'el-salvador': `https://www.getnomad.app/el-salvador-eSIM${NOMAD_BASE_PARAMS}`,
  'emirati-arabi-uniti': `https://www.getnomad.app/united-arab-emirates-eSIM${NOMAD_BASE_PARAMS}`,
  'estonia': `https://www.getnomad.app/estonia-eSIM${NOMAD_BASE_PARAMS}`,
  'etiopia': `https://www.getnomad.app/ethiopia-eSIM${NOMAD_BASE_PARAMS}`,
  'figi': `https://www.getnomad.app/fiji-eSIM${NOMAD_BASE_PARAMS}`,
  'filippine': `https://www.getnomad.app/philippines-eSIM${NOMAD_BASE_PARAMS}`,
  'finlandia': `https://www.getnomad.app/finland-eSIM${NOMAD_BASE_PARAMS}`,
  'francia': `https://www.getnomad.app/france-eSIM${NOMAD_BASE_PARAMS}`,
  'gabon': `https://www.getnomad.app/gabon-eSIM${NOMAD_BASE_PARAMS}`,
  'gambia': `https://www.getnomad.app/gambia-eSIM${NOMAD_BASE_PARAMS}`,
  'georgia': `https://www.getnomad.app/georgia-eSIM${NOMAD_BASE_PARAMS}`,
  'germania': `https://www.getnomad.app/germany-eSIM${NOMAD_BASE_PARAMS}`,
  'ghana': `https://www.getnomad.app/ghana-eSIM${NOMAD_BASE_PARAMS}`,
  'giamaica': `https://www.getnomad.app/jamaica-eSIM${NOMAD_BASE_PARAMS}`,
  'giappone': `https://www.getnomad.app/japan-eSIM${NOMAD_BASE_PARAMS}`,
  'gibilterra': `https://www.getnomad.app/gibraltar-eSIM${NOMAD_BASE_PARAMS}`,
  'giordania': `https://www.getnomad.app/jordan-eSIM${NOMAD_BASE_PARAMS}`,
  'grenada': `https://www.getnomad.app/grenada-eSIM${NOMAD_BASE_PARAMS}`,
  'grecia': `https://www.getnomad.app/greece-eSIM${NOMAD_BASE_PARAMS}`,
  'groenlandia': `https://www.getnomad.app/greenland-eSIM${NOMAD_BASE_PARAMS}`,
  'guadalupa': `https://www.getnomad.app/guadeloupe-eSIM${NOMAD_BASE_PARAMS}`,
  'guam': `https://www.getnomad.app/guam-eSIM${NOMAD_BASE_PARAMS}`,
  'guatemala': `https://www.getnomad.app/guatemala-eSIM${NOMAD_BASE_PARAMS}`,
  'guernsey': `https://www.getnomad.app/guernsey-eSIM${NOMAD_BASE_PARAMS}`,
  'guyana-francese': `https://www.getnomad.app/french-guiana-eSIM${NOMAD_BASE_PARAMS}`,
  'guinea': `https://www.getnomad.app/guinea-eSIM${NOMAD_BASE_PARAMS}`,
  'guinea-bissau': `https://www.getnomad.app/guinea-bissau-eSIM${NOMAD_BASE_PARAMS}`,
  'guyana': `https://www.getnomad.app/guyana-eSIM${NOMAD_BASE_PARAMS}`,
  'haiti': `https://www.getnomad.app/haiti-eSIM${NOMAD_BASE_PARAMS}`,
  'honduras': `https://www.getnomad.app/honduras-eSIM${NOMAD_BASE_PARAMS}`,
  'india': `https://www.getnomad.app/india-eSIM${NOMAD_BASE_PARAMS}`,
  'indonesia': `https://www.getnomad.app/indonesia-eSIM${NOMAD_BASE_PARAMS}`,
  'iran': `https://www.getnomad.app/iran-eSIM${NOMAD_BASE_PARAMS}`,
  'iraq': `https://www.getnomad.app/iraq-eSIM${NOMAD_BASE_PARAMS}`,
  'irlanda': `https://www.getnomad.app/ireland-eSIM${NOMAD_BASE_PARAMS}`,
  'islanda': `https://www.getnomad.app/iceland-eSIM${NOMAD_BASE_PARAMS}`,
  'isola-di-man': `https://www.getnomad.app/isle-of-man-eSIM${NOMAD_BASE_PARAMS}`,
  'isole-cayman': `https://www.getnomad.app/cayman-islands-eSIM${NOMAD_BASE_PARAMS}`,
  'isole-faroe': `https://www.getnomad.app/faroe-islands-eSIM${NOMAD_BASE_PARAMS}`,
  'isole-salomone': `https://www.getnomad.app/solomon-islands-eSIM${NOMAD_BASE_PARAMS}`,
  'isole-turks-e-caicos': `https://www.getnomad.app/turks-and-caicos-islands-eSIM${NOMAD_BASE_PARAMS}`,
  'isole-vergini-britanniche': `https://www.getnomad.app/british-virgin-islands-eSIM${NOMAD_BASE_PARAMS}`,
  'isole-vergini-americane': `https://www.getnomad.app/us-virgin-islands-eSIM${NOMAD_BASE_PARAMS}`,
  'israele': `https://www.getnomad.app/israel-eSIM${NOMAD_BASE_PARAMS}`,
  'italia': `https://www.getnomad.app/italy-eSIM${NOMAD_BASE_PARAMS}`,
  'kazakistan': `https://www.getnomad.app/kazakhstan-eSIM${NOMAD_BASE_PARAMS}`,
  'kenya': `https://www.getnomad.app/kenya-eSIM${NOMAD_BASE_PARAMS}`,
  'kirghizistan': `https://www.getnomad.app/kyrgyzstan-eSIM${NOMAD_BASE_PARAMS}`,
  'kiribati': `https://www.getnomad.app/kiribati-eSIM${NOMAD_BASE_PARAMS}`,
  'kosovo': `https://www.getnomad.app/kosovo-eSIM${NOMAD_BASE_PARAMS}`,
  'kuwait': `https://www.getnomad.app/kuwait-eSIM${NOMAD_BASE_PARAMS}`,
  'laos': `https://www.getnomad.app/laos-eSIM${NOMAD_BASE_PARAMS}`,
  'lesotho': `https://www.getnomad.app/lesotho-eSIM${NOMAD_BASE_PARAMS}`,
  'lettonia': `https://www.getnomad.app/latvia-eSIM${NOMAD_BASE_PARAMS}`,
  'liberia': `https://www.getnomad.app/liberia-eSIM${NOMAD_BASE_PARAMS}`,
  'liechtenstein': `https://www.getnomad.app/liechtenstein-eSIM${NOMAD_BASE_PARAMS}`,
  'lituania': `https://www.getnomad.app/lithuania-eSIM${NOMAD_BASE_PARAMS}`,
  'lussemburgo': `https://www.getnomad.app/luxembourg-eSIM${NOMAD_BASE_PARAMS}`,
  'macedonia-del-nord': `https://www.getnomad.app/north-macedonia-eSIM${NOMAD_BASE_PARAMS}`,
  'madagascar': `https://www.getnomad.app/madagascar-eSIM${NOMAD_BASE_PARAMS}`,
  'malawi': `https://www.getnomad.app/malawi-eSIM${NOMAD_BASE_PARAMS}`,
  'malaysia': `https://www.getnomad.app/malaysia-eSIM${NOMAD_BASE_PARAMS}`,
  'maldive': `https://www.getnomad.app/maldives-eSIM${NOMAD_BASE_PARAMS}`,
  'mali': `https://www.getnomad.app/mali-eSIM${NOMAD_BASE_PARAMS}`,
  'malta': `https://www.getnomad.app/malta-eSIM${NOMAD_BASE_PARAMS}`,
  'marocco': `https://www.getnomad.app/morocco-eSIM${NOMAD_BASE_PARAMS}`,
  'martinica': `https://www.getnomad.app/martinique-eSIM${NOMAD_BASE_PARAMS}`,
  'mauritania': `https://www.getnomad.app/mauritania-eSIM${NOMAD_BASE_PARAMS}`,
  'mauritius': `https://www.getnomad.app/mauritius-eSIM${NOMAD_BASE_PARAMS}`,
  'mayotte': `https://www.getnomad.app/mayotte-eSIM${NOMAD_BASE_PARAMS}`,
  'messico': `https://www.getnomad.app/mexico-eSIM${NOMAD_BASE_PARAMS}`,
  'moldavia': `https://www.getnomad.app/moldova-eSIM${NOMAD_BASE_PARAMS}`,
  'monaco': `https://www.getnomad.app/monaco-eSIM${NOMAD_BASE_PARAMS}`,
  'mongolia': `https://www.getnomad.app/mongolia-eSIM${NOMAD_BASE_PARAMS}`,
  'montenegro': `https://www.getnomad.app/montenegro-eSIM${NOMAD_BASE_PARAMS}`,
  'montserrat': `https://www.getnomad.app/montserrat-eSIM${NOMAD_BASE_PARAMS}`,
  'mozambico': `https://www.getnomad.app/mozambique-eSIM${NOMAD_BASE_PARAMS}`,
  'namibia': `https://www.getnomad.app/namibia-eSIM${NOMAD_BASE_PARAMS}`,
  'nauru': `https://www.getnomad.app/nauru-eSIM${NOMAD_BASE_PARAMS}`,
  'nepal': `https://www.getnomad.app/nepal-eSIM${NOMAD_BASE_PARAMS}`,
  'nicaragua': `https://www.getnomad.app/nicaragua-eSIM${NOMAD_BASE_PARAMS}`,
  'niger': `https://www.getnomad.app/niger-eSIM${NOMAD_BASE_PARAMS}`,
  'nigeria': `https://www.getnomad.app/nigeria-eSIM${NOMAD_BASE_PARAMS}`,
  'norvegia': `https://www.getnomad.app/norway-eSIM${NOMAD_BASE_PARAMS}`,
  'nuova-caledonia': `https://www.getnomad.app/new-caledonia-eSIM${NOMAD_BASE_PARAMS}`,
  'nuova-zelanda': `https://www.getnomad.app/new-zealand-eSIM${NOMAD_BASE_PARAMS}`,
  'olanda': `https://www.getnomad.app/netherlands-eSIM${NOMAD_BASE_PARAMS}`,
  'oman': `https://www.getnomad.app/oman-eSIM${NOMAD_BASE_PARAMS}`,
  'pakistan': `https://www.getnomad.app/pakistan-eSIM${NOMAD_BASE_PARAMS}`,
  'palau': `https://www.getnomad.app/palau-eSIM${NOMAD_BASE_PARAMS}`,
  'panama': `https://www.getnomad.app/panama-eSIM${NOMAD_BASE_PARAMS}`,
  'papua-nuova-guinea': `https://www.getnomad.app/papua-new-guinea-eSIM${NOMAD_BASE_PARAMS}`,
  'paraguay': `https://www.getnomad.app/paraguay-eSIM${NOMAD_BASE_PARAMS}`,
  'peru': `https://www.getnomad.app/peru-eSIM${NOMAD_BASE_PARAMS}`,
  'polinesia-francese': `https://www.getnomad.app/french-polynesia-eSIM${NOMAD_BASE_PARAMS}`,
  'polonia': `https://www.getnomad.app/poland-eSIM${NOMAD_BASE_PARAMS}`,
  'portogallo': `https://www.getnomad.app/portugal-eSIM${NOMAD_BASE_PARAMS}`,
  'puerto-rico': `https://www.getnomad.app/puerto-rico-eSIM${NOMAD_BASE_PARAMS}`,
  'qatar': `https://www.getnomad.app/qatar-eSIM${NOMAD_BASE_PARAMS}`,
  'macao': `https://www.getnomad.app/macao-eSIM${NOMAD_BASE_PARAMS}`,
  'regno-unito': `https://www.getnomad.app/united-kingdom-eSIM${NOMAD_BASE_PARAMS}`,
  'repubblica-centrafricana': `https://www.getnomad.app/central-african-republic-eSIM${NOMAD_BASE_PARAMS}`,
  'repubblica-dominicana': `https://www.getnomad.app/dominican-republic-eSIM${NOMAD_BASE_PARAMS}`,
  'romania': `https://www.getnomad.app/romania-eSIM${NOMAD_BASE_PARAMS}`,
  'ruanda': `https://www.getnomad.app/rwanda-eSIM${NOMAD_BASE_PARAMS}`,
  'russia': `https://www.getnomad.app/russia-eSIM${NOMAD_BASE_PARAMS}`,
  'saint-kitts-e-nevis': `https://www.getnomad.app/saint-kitts-and-nevis-eSIM${NOMAD_BASE_PARAMS}`,
  'saint-vincent-e-grenadine': `https://www.getnomad.app/saint-vincent-and-the-grenadines-eSIM${NOMAD_BASE_PARAMS}`,
  'samoa': `https://www.getnomad.app/samoa-eSIM${NOMAD_BASE_PARAMS}`,
  'samoa-americane': `https://www.getnomad.app/american-samoa-eSIM${NOMAD_BASE_PARAMS}`,
  'san-marino': `https://www.getnomad.app/san-marino-eSIM${NOMAD_BASE_PARAMS}`,
  'saint-martin': `https://www.getnomad.app/saint-martin-eSIM${NOMAD_BASE_PARAMS}`,
  'santa-lucia': `https://www.getnomad.app/saint-lucia-eSIM${NOMAD_BASE_PARAMS}`,
  'senegal': `https://www.getnomad.app/senegal-eSIM${NOMAD_BASE_PARAMS}`,
  'serbia': `https://www.getnomad.app/serbia-eSIM${NOMAD_BASE_PARAMS}`,
  'seychelles': `https://www.getnomad.app/seychelles-eSIM${NOMAD_BASE_PARAMS}`,
  'sierra-leone': `https://www.getnomad.app/sierra-leone-eSIM${NOMAD_BASE_PARAMS}`,
  'singapore': `https://www.getnomad.app/singapore-eSIM${NOMAD_BASE_PARAMS}`,
  'slovacchia': `https://www.getnomad.app/slovakia-eSIM${NOMAD_BASE_PARAMS}`,
  'slovenia': `https://www.getnomad.app/slovenia-eSIM${NOMAD_BASE_PARAMS}`,
  'spagna': `https://www.getnomad.app/spain-eSIM${NOMAD_BASE_PARAMS}`,
  'sri-lanka': `https://www.getnomad.app/sri-lanka-eSIM${NOMAD_BASE_PARAMS}`,
  'saint-barthelemy': `https://www.getnomad.app/saint-barthelemy-eSIM${NOMAD_BASE_PARAMS}`,
  'stati-uniti': `https://www.getnomad.app/united-states-eSIM${NOMAD_BASE_PARAMS}`,
  'sudafrica': `https://www.getnomad.app/south-africa-eSIM${NOMAD_BASE_PARAMS}`,
  'sudan': `https://www.getnomad.app/sudan-eSIM${NOMAD_BASE_PARAMS}`,
  'sudan-del-sud': `https://www.getnomad.app/south-sudan-eSIM${NOMAD_BASE_PARAMS}`,
  'suriname': `https://www.getnomad.app/suriname-eSIM${NOMAD_BASE_PARAMS}`,
  'svezia': `https://www.getnomad.app/sweden-eSIM${NOMAD_BASE_PARAMS}`,
  'svizzera': `https://www.getnomad.app/switzerland-eSIM${NOMAD_BASE_PARAMS}`,
  'eswatini': `https://www.getnomad.app/eswatini-eSIM${NOMAD_BASE_PARAMS}`,
  'tagikistan': `https://www.getnomad.app/tajikistan-eSIM${NOMAD_BASE_PARAMS}`,
  'tailandia': `https://www.getnomad.app/thailand-eSIM${NOMAD_BASE_PARAMS}`,
  'taiwan': `https://www.getnomad.app/taiwan-eSIM${NOMAD_BASE_PARAMS}`,
  'tanzania': `https://www.getnomad.app/tanzania-eSIM${NOMAD_BASE_PARAMS}`,
  'palestina': `https://www.getnomad.app/palestine-eSIM${NOMAD_BASE_PARAMS}`,
  'timor-est': `https://www.getnomad.app/timor-leste-eSIM${NOMAD_BASE_PARAMS}`,
  'tonga': `https://www.getnomad.app/tonga-eSIM${NOMAD_BASE_PARAMS}`,
  'trinidad-e-tobago': `https://www.getnomad.app/trinidad-and-tobago-eSIM${NOMAD_BASE_PARAMS}`,
  'tunisia': `https://www.getnomad.app/tunisia-eSIM${NOMAD_BASE_PARAMS}`,
  'turchia': `https://www.getnomad.app/turkey-eSIM${NOMAD_BASE_PARAMS}`,
  'ucraina': `https://www.getnomad.app/ukraine-eSIM${NOMAD_BASE_PARAMS}`,
  'uganda': `https://www.getnomad.app/uganda-eSIM${NOMAD_BASE_PARAMS}`,
  'ungheria': `https://www.getnomad.app/hungary-eSIM${NOMAD_BASE_PARAMS}`,
  'uruguay': `https://www.getnomad.app/uruguay-eSIM${NOMAD_BASE_PARAMS}`,
  'uzbekistan': `https://www.getnomad.app/uzbekistan-eSIM${NOMAD_BASE_PARAMS}`,
  'vanuatu': `https://www.getnomad.app/vanuatu-eSIM${NOMAD_BASE_PARAMS}`,
  'venezuela': `https://www.getnomad.app/venezuela-eSIM${NOMAD_BASE_PARAMS}`,
  'vietnam': `https://www.getnomad.app/vietnam-eSIM${NOMAD_BASE_PARAMS}`,
  'yemen': `https://www.getnomad.app/yemen-eSIM${NOMAD_BASE_PARAMS}`,
  'zambia': `https://www.getnomad.app/zambia-eSIM${NOMAD_BASE_PARAMS}`,
  'zimbabwe': `https://www.getnomad.app/zimbabwe-eSIM${NOMAD_BASE_PARAMS}`
};

// Generic Nomad affiliate link (fallback)
export const NOMAD_GENERIC_AFFILIATE = 'https://finanza.me/nomad';

/**
 * Get the appropriate Nomad affiliate link for a given country
 * @param country - The country name (normalized to lowercase with hyphens)
 * @returns The specific affiliate link for the country, or the generic link if not found
 */
export function getNomadAffiliateLink(country?: string): string {
  if (!country) {
    return NOMAD_GENERIC_AFFILIATE;
  }

  // Normalize country name: lowercase and replace spaces with hyphens
  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  
  return NOMAD_AFFILIATE_MAPPING[normalizedCountry] || NOMAD_GENERIC_AFFILIATE;
}

/**
 * Check if a country has a specific Nomad affiliate link
 * @param country - The country name
 * @returns True if a specific affiliate link exists, false otherwise
 */
export function hasSpecificNomadLink(country?: string): boolean {
  if (!country) {
    return false;
  }

  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  return normalizedCountry in NOMAD_AFFILIATE_MAPPING;
}
