// Saily Country-Specific Affiliate Links Mapping
// This file contains the mapping from country names to their specific Saily affiliate links

export interface SailyAffiliateMapping {
  [countryKey: string]: string;
}

// Base parameters for all Saily links
const SAILY_BASE_PARAMS = '?utm_source=9135&utm_medium=affiliate&utm_campaign=101&aff_transaction_id=1021692cf327c046146e4cb09ae67a&aff_sub=&aff_offer_id=101&aff_id=9135&utm_content=&params%5Bho_asub1%5D=';

// Country name to Saily affiliate link mapping
export const SAILY_AFFILIATE_MAPPING: SailyAffiliateMapping = {
  'afghanistan': `https://saily.com/it/esim-afghanistan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-afghanistan%2F`,
  'albania': `https://saily.com/it/esim-albania/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-albania%2F`,
  'algeria': `https://saily.com/it/esim-algeria/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-algeria%2F`,
  'andorra': `https://saily.com/it/esim-andorra/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-andorra%2F`,
  'angola': `https://saily.com/it/esim-angola/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-angola%2F`,
  'anguilla': `https://saily.com/it/esim-anguilla/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-anguilla%2F`,
  'antigua-e-barbuda': `https://saily.com/it/esim-antigua-and-barbuda/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-antigua-and-barbuda%2F`,
  'arabia-saudita': `https://saily.com/it/esim-saudi-arabia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-saudi-arabia%2F`,
  'argentina': `https://saily.com/it/esim-argentina/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-argentina%2F`,
  'armenia': `https://saily.com/it/esim-armenia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-armenia%2F`,
  'aruba': `https://saily.com/it/esim-aruba/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-aruba%2F`,
  'australia': `https://saily.com/it/esim-australia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-australia%2F`,
  'austria': `https://saily.com/it/esim-austria/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-austria%2F`,
  'azerbaigian': `https://saily.com/it/esim-azerbaijan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-azerbaijan%2F`,
  'bahamas': `https://saily.com/it/esim-bahamas/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bahamas%2F`,
  'bahrain': `https://saily.com/it/esim-bahrain/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bahrain%2F`,
  'bangladesh': `https://saily.com/it/esim-bangladesh/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bangladesh%2F`,
  'barbados': `https://saily.com/it/esim-barbados/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-barbados%2F`,
  'belgio': `https://saily.com/it/esim-belgium/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-belgium%2F`,
  'belize': `https://saily.com/it/esim-belize/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-belize%2F`,
  'benin': `https://saily.com/it/esim-benin/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-benin%2F`,
  'bermuda': `https://saily.com/it/esim-bermuda/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bermuda%2F`,
  'bhutan': `https://saily.com/it/esim-bhutan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bhutan%2F`,
  'bielorussia': `https://saily.com/it/esim-belarus/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-belarus%2F`,
  'bolivia': `https://saily.com/it/esim-bolivia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bolivia%2F`,
  'bosnia-ed-erzegovina': `https://saily.com/it/esim-bosnia-and-herzegovina/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bosnia-and-herzegovina%2F`,
  'botswana': `https://saily.com/it/esim-botswana/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-botswana%2F`,
  'brasile': `https://saily.com/it/esim-brazil/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-brazil%2F`,
  'brunei': `https://saily.com/it/esim-brunei/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-brunei%2F`,
  'bulgaria': `https://saily.com/it/esim-bulgaria/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-bulgaria%2F`,
  'burkina-faso': `https://saily.com/it/esim-burkina-faso/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-burkina-faso%2F`,
  'burundi': `https://saily.com/it/esim-burundi/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-burundi%2F`,
  'cambogia': `https://saily.com/it/esim-cambodia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cambodia%2F`,
  'camerun': `https://saily.com/it/esim-cameroon/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cameroon%2F`,
  'canada': `https://saily.com/it/esim-canada/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-canada%2F`,
  'capo-verde': `https://saily.com/it/esim-cape-verde/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cape-verde%2F`,
  'repubblica-ceca': `https://saily.com/it/esim-czech-republic/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-czech-republic%2F`,
  'chad': `https://saily.com/it/esim-chad/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-chad%2F`,
  'cile': `https://saily.com/it/esim-chile/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-chile%2F`,
  'cina': `https://saily.com/it/esim-china/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-china%2F`,
  'hong-kong': `https://saily.com/it/esim-hong-kong/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-hong-kong%2F`,
  'cipro': `https://saily.com/it/esim-cyprus/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cyprus%2F`,
  'vaticano': `https://saily.com/it/esim-vatican-city/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-vatican-city%2F`,
  'colombia': `https://saily.com/it/esim-colombia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-colombia%2F`,
  'comore': `https://saily.com/it/esim-comoros/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-comoros%2F`,
  'congo-brazzaville': `https://saily.com/it/esim-republic-of-congo/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-republic-of-congo%2F`,
  'congo-kinshasa': `https://saily.com/it/esim-democratic-republic-of-congo/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-democratic-republic-of-congo%2F`,
  'corea-del-sud': `https://saily.com/it/esim-south-korea/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-south-korea%2F`,
  'costa-rica': `https://saily.com/it/esim-costa-rica/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-costa-rica%2F`,
  'costa-d-avorio': `https://saily.com/it/esim-cote-d-ivoire/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cote-d-ivoire%2F`,
  'croazia': `https://saily.com/it/esim-croatia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-croatia%2F`,
  'cuba': `https://saily.com/it/esim-cuba/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cuba%2F`,
  'curacao': `https://saily.com/it/esim-curacao/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-curacao%2F`,
  'danimarca': `https://saily.com/it/esim-denmark/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-denmark%2F`,
  'dominica': `https://saily.com/it/esim-dominica/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-dominica%2F`,
  'ecuador': `https://saily.com/it/esim-ecuador/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-ecuador%2F`,
  'egitto': `https://saily.com/it/esim-egypt/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-egypt%2F`,
  'el-salvador': `https://saily.com/it/esim-el-salvador/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-el-salvador%2F`,
  'emirati-arabi-uniti': `https://saily.com/it/esim-united-arab-emirates/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-united-arab-emirates%2F`,
  'estonia': `https://saily.com/it/esim-estonia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-estonia%2F`,
  'etiopia': `https://saily.com/it/esim-ethiopia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-ethiopia%2F`,
  'figi': `https://saily.com/it/esim-fiji/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-fiji%2F`,
  'filippine': `https://saily.com/it/esim-philippines/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-philippines%2F`,
  'finlandia': `https://saily.com/it/esim-finland/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-finland%2F`,
  'francia': `https://saily.com/it/esim-france/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-france%2F`,
  'gabon': `https://saily.com/it/esim-gabon/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-gabon%2F`,
  'gambia': `https://saily.com/it/esim-gambia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-gambia%2F`,
  'georgia': `https://saily.com/it/esim-georgia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-georgia%2F`,
  'germania': `https://saily.com/it/esim-germany/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-germany%2F`,
  'ghana': `https://saily.com/it/esim-ghana/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-ghana%2F`,
  'giamaica': `https://saily.com/it/esim-jamaica/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-jamaica%2F`,
  'giappone': `https://saily.com/it/esim-japan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-japan%2F`,
  'gibilterra': `https://saily.com/it/esim-gibraltar/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-gibraltar%2F`,
  'giordania': `https://saily.com/it/esim-jordan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-jordan%2F`,
  'grenada': `https://saily.com/it/esim-grenada/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-grenada%2F`,
  'grecia': `https://saily.com/it/esim-greece/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-greece%2F`,
  'groenlandia': `https://saily.com/it/esim-greenland/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-greenland%2F`,
  'guadalupa': `https://saily.com/it/esim-guadeloupe/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guadeloupe%2F`,
  'guam': `https://saily.com/it/esim-guam/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guam%2F`,
  'guatemala': `https://saily.com/it/esim-guatemala/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guatemala%2F`,
  'guernsey': `https://saily.com/it/esim-guernsey/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guernsey%2F`,
  'guyana-francese': `https://saily.com/it/esim-french-guiana/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-french-guiana%2F`,
  'guinea': `https://saily.com/it/esim-guinea/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guinea%2F`,
  'guinea-bissau': `https://saily.com/it/esim-guinea-bissau/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guinea-bissau%2F`,
  'guyana': `https://saily.com/it/esim-guyana/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-guyana%2F`,
  'haiti': `https://saily.com/it/esim-haiti/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-haiti%2F`,
  'honduras': `https://saily.com/it/esim-honduras/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-honduras%2F`,
  'india': `https://saily.com/it/esim-india/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-india%2F`,
  'indonesia': `https://saily.com/it/esim-indonesia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-indonesia%2F`,
  'iran': `https://saily.com/it/esim-iran/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-iran%2F`,
  'iraq': `https://saily.com/it/esim-iraq/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-iraq%2F`,
  'irlanda': `https://saily.com/it/esim-ireland/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-ireland%2F`,
  'islanda': `https://saily.com/it/esim-iceland/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-iceland%2F`,
  'isola-di-man': `https://saily.com/it/esim-isle-of-man/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-isle-of-man%2F`,
  'isole-cayman': `https://saily.com/it/esim-cayman-islands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-cayman-islands%2F`,
  'isole-faroe': `https://saily.com/it/esim-faroe-islands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-faroe-islands%2F`,
  'isole-salomone': `https://saily.com/it/esim-solomon-islands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-solomon-islands%2F`,
  'isole-turks-e-caicos': `https://saily.com/it/esim-turks-and-caicos-islands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-turks-and-caicos-islands%2F`,
  'isole-vergini-britanniche': `https://saily.com/it/esim-british-virgin-islands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-british-virgin-islands%2F`,
  'isole-vergini-americane': `https://saily.com/it/esim-us-virgin-islands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-us-virgin-islands%2F`,
  'israele': `https://saily.com/it/esim-israel/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-israel%2F`,
  'italia': `https://saily.com/it/esim-italy/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-italy%2F`,
  'kazakistan': `https://saily.com/it/esim-kazakhstan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-kazakhstan%2F`,
  'kenya': `https://saily.com/it/esim-kenya/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-kenya%2F`,
  'kirghizistan': `https://saily.com/it/esim-kyrgyzstan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-kyrgyzstan%2F`,
  'kiribati': `https://saily.com/it/esim-kiribati/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-kiribati%2F`,
  'kosovo': `https://saily.com/it/esim-kosovo/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-kosovo%2F`,
  'kuwait': `https://saily.com/it/esim-kuwait/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-kuwait%2F`,
  'laos': `https://saily.com/it/esim-laos/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-laos%2F`,
  'lesotho': `https://saily.com/it/esim-lesotho/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-lesotho%2F`,
  'lettonia': `https://saily.com/it/esim-latvia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-latvia%2F`,
  'liberia': `https://saily.com/it/esim-liberia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-liberia%2F`,
  'liechtenstein': `https://saily.com/it/esim-liechtenstein/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-liechtenstein%2F`,
  'lituania': `https://saily.com/it/esim-lithuania/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-lithuania%2F`,
  'lussemburgo': `https://saily.com/it/esim-luxembourg/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-luxembourg%2F`,
  'macedonia-del-nord': `https://saily.com/it/esim-north-macedonia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-north-macedonia%2F`,
  'madagascar': `https://saily.com/it/esim-madagascar/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-madagascar%2F`,
  'malawi': `https://saily.com/it/esim-malawi/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-malawi%2F`,
  'malaysia': `https://saily.com/it/esim-malaysia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-malaysia%2F`,
  'maldive': `https://saily.com/it/esim-maldives/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-maldives%2F`,
  'mali': `https://saily.com/it/esim-mali/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mali%2F`,
  'malta': `https://saily.com/it/esim-malta/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-malta%2F`,
  'marocco': `https://saily.com/it/esim-morocco/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-morocco%2F`,
  'martinica': `https://saily.com/it/esim-martinique/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-martinique%2F`,
  'mauritania': `https://saily.com/it/esim-mauritania/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mauritania%2F`,
  'mauritius': `https://saily.com/it/esim-mauritius/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mauritius%2F`,
  'mayotte': `https://saily.com/it/esim-mayotte/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mayotte%2F`,
  'messico': `https://saily.com/it/esim-mexico/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mexico%2F`,
  'moldavia': `https://saily.com/it/esim-moldova/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-moldova%2F`,
  'monaco': `https://saily.com/it/esim-monaco/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-monaco%2F`,
  'mongolia': `https://saily.com/it/esim-mongolia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mongolia%2F`,
  'montenegro': `https://saily.com/it/esim-montenegro/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-montenegro%2F`,
  'montserrat': `https://saily.com/it/esim-montserrat/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-montserrat%2F`,
  'mozambico': `https://saily.com/it/esim-mozambique/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-mozambique%2F`,
  'namibia': `https://saily.com/it/esim-namibia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-namibia%2F`,
  'nauru': `https://saily.com/it/esim-nauru/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-nauru%2F`,
  'nepal': `https://saily.com/it/esim-nepal/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-nepal%2F`,
  'nicaragua': `https://saily.com/it/esim-nicaragua/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-nicaragua%2F`,
  'niger': `https://saily.com/it/esim-niger/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-niger%2F`,
  'nigeria': `https://saily.com/it/esim-nigeria/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-nigeria%2F`,
  'norvegia': `https://saily.com/it/esim-norway/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-norway%2F`,
  'nuova-caledonia': `https://saily.com/it/esim-new-caledonia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-new-caledonia%2F`,
  'nuova-zelanda': `https://saily.com/it/esim-new-zealand/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-new-zealand%2F`,
  'olanda': `https://saily.com/it/esim-netherlands/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-netherlands%2F`,
  'oman': `https://saily.com/it/esim-oman/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-oman%2F`,
  'pakistan': `https://saily.com/it/esim-pakistan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-pakistan%2F`,
  'palau': `https://saily.com/it/esim-palau/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-palau%2F`,
  'panama': `https://saily.com/it/esim-panama/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-panama%2F`,
  'papua-nuova-guinea': `https://saily.com/it/esim-papua-new-guinea/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-papua-new-guinea%2F`,
  'paraguay': `https://saily.com/it/esim-paraguay/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-paraguay%2F`,
  'peru': `https://saily.com/it/esim-peru/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-peru%2F`,
  'polinesia-francese': `https://saily.com/it/esim-french-polynesia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-french-polynesia%2F`,
  'polonia': `https://saily.com/it/esim-poland/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-poland%2F`,
  'portogallo': `https://saily.com/it/esim-portugal/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-portugal%2F`,
  'puerto-rico': `https://saily.com/it/esim-puerto-rico/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-puerto-rico%2F`,
  'qatar': `https://saily.com/it/esim-qatar/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-qatar%2F`,
  'macao': `https://saily.com/it/esim-macao/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-macao%2F`,
  'regno-unito': `https://saily.com/it/esim-united-kingdom/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-united-kingdom%2F`,
  'repubblica-centrafricana': `https://saily.com/it/esim-central-african-republic/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-central-african-republic%2F`,
  'repubblica-dominicana': `https://saily.com/it/esim-dominican-republic/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-dominican-republic%2F`,
  'romania': `https://saily.com/it/esim-romania/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-romania%2F`,
  'ruanda': `https://saily.com/it/esim-rwanda/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-rwanda%2F`,
  'russia': `https://saily.com/it/esim-russia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-russia%2F`,
  'saint-kitts-e-nevis': `https://saily.com/it/esim-saint-kitts-and-nevis/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-saint-kitts-and-nevis%2F`,
  'saint-vincent-e-grenadine': `https://saily.com/it/esim-saint-vincent-and-the-grenadines/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-saint-vincent-and-the-grenadines%2F`,
  'samoa': `https://saily.com/it/esim-samoa/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-samoa%2F`,
  'samoa-americane': `https://saily.com/it/esim-american-samoa/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-american-samoa%2F`,
  'san-marino': `https://saily.com/it/esim-san-marino/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-san-marino%2F`,
  'saint-martin': `https://saily.com/it/esim-saint-martin/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-saint-martin%2F`,
  'santa-lucia': `https://saily.com/it/esim-saint-lucia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-saint-lucia%2F`,
  'senegal': `https://saily.com/it/esim-senegal/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-senegal%2F`,
  'serbia': `https://saily.com/it/esim-serbia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-serbia%2F`,
  'seychelles': `https://saily.com/it/esim-seychelles/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-seychelles%2F`,
  'sierra-leone': `https://saily.com/it/esim-sierra-leone/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-sierra-leone%2F`,
  'singapore': `https://saily.com/it/esim-singapore/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-singapore%2F`,
  'slovacchia': `https://saily.com/it/esim-slovakia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-slovakia%2F`,
  'slovenia': `https://saily.com/it/esim-slovenia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-slovenia%2F`,
  'spagna': `https://saily.com/it/esim-spain/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-spain%2F`,
  'sri-lanka': `https://saily.com/it/esim-sri-lanka/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-sri-lanka%2F`,
  'saint-barthelemy': `https://saily.com/it/esim-saint-barthelemy/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-saint-barthelemy%2F`,
  'stati-uniti': `https://saily.com/it/esim-united-states/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-united-states%2F`,
  'sudafrica': `https://saily.com/it/esim-south-africa/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-south-africa%2F`,
  'sudan': `https://saily.com/it/esim-sudan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-sudan%2F`,
  'sudan-del-sud': `https://saily.com/it/esim-south-sudan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-south-sudan%2F`,
  'suriname': `https://saily.com/it/esim-suriname/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-suriname%2F`,
  'svezia': `https://saily.com/it/esim-sweden/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-sweden%2F`,
  'svizzera': `https://saily.com/it/esim-switzerland/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-switzerland%2F`,
  'eswatini': `https://saily.com/it/esim-eswatini/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-eswatini%2F`,
  'tagikistan': `https://saily.com/it/esim-tajikistan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-tajikistan%2F`,
  'tailandia': `https://saily.com/it/esim-thailand/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-thailand%2F`,
  'taiwan': `https://saily.com/it/esim-taiwan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-taiwan%2F`,
  'tanzania': `https://saily.com/it/esim-tanzania/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-tanzania%2F`,
  'palestina': `https://saily.com/it/esim-palestine/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-palestine%2F`,
  'timor-est': `https://saily.com/it/esim-timor-leste/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-timor-leste%2F`,
  'tonga': `https://saily.com/it/esim-tonga/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-tonga%2F`,
  'trinidad-e-tobago': `https://saily.com/it/esim-trinidad-and-tobago/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-trinidad-and-tobago%2F`,
  'tunisia': `https://saily.com/it/esim-tunisia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-tunisia%2F`,
  'turchia': `https://saily.com/it/esim-turkey/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-turkey%2F`,
  'ucraina': `https://saily.com/it/esim-ukraine/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-ukraine%2F`,
  'uganda': `https://saily.com/it/esim-uganda/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-uganda%2F`,
  'ungheria': `https://saily.com/it/esim-hungary/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-hungary%2F`,
  'uruguay': `https://saily.com/it/esim-uruguay/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-uruguay%2F`,
  'uzbekistan': `https://saily.com/it/esim-uzbekistan/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-uzbekistan%2F`,
  'vanuatu': `https://saily.com/it/esim-vanuatu/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-vanuatu%2F`,
  'venezuela': `https://saily.com/it/esim-venezuela/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-venezuela%2F`,
  'vietnam': `https://saily.com/it/esim-vietnam/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-vietnam%2F`,
  'yemen': `https://saily.com/it/esim-yemen/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-yemen%2F`,
  'zambia': `https://saily.com/it/esim-zambia/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-zambia%2F`,
  'zimbabwe': `https://saily.com/it/esim-zimbabwe/${SAILY_BASE_PARAMS}&url=https%3A%2F%2Fsaily.com%2Fit%2Fesim-zimbabwe%2F`
};

// Generic Saily affiliate link (fallback)
export const SAILY_GENERIC_AFFILIATE = 'https://finanza.me/saily';

/**
 * Get the appropriate Saily affiliate link for a given country
 * @param country - The country name (normalized to lowercase with hyphens)
 * @returns The specific affiliate link for the country, or the generic link if not found
 */
export function getSailyAffiliateLink(country?: string): string {
  if (!country) {
    return SAILY_GENERIC_AFFILIATE;
  }

  // Normalize country name: lowercase and replace spaces with hyphens
  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  
  return SAILY_AFFILIATE_MAPPING[normalizedCountry] || SAILY_GENERIC_AFFILIATE;
}

/**
 * Check if a country has a specific Saily affiliate link
 * @param country - The country name
 * @returns True if a specific affiliate link exists, false otherwise
 */
export function hasSpecificSailyLink(country?: string): boolean {
  if (!country) {
    return false;
  }

  const normalizedCountry = country.toLowerCase().replace(/\s+/g, '-');
  return normalizedCountry in SAILY_AFFILIATE_MAPPING;
}
