/**
 * Yesim Affiliate Link Mapping per Paese
 * 
 * Questo file gestisce il mapping dei link affiliati Yesim specifici per ogni paese.
 * Quando un utente clicca su un'offerta Yesim, viene reindirizzato al link specifico
 * del paese con i parametri di tracking affiliato.
 */

// Parametri base per tutti i link Yesim
const YESIM_BASE_PARAMS = '?partner_id=1639';

// Mapping completo dei link Yesim per ogni paese
export const YESIM_AFFILIATE_MAPPING: Record<string, string> = {
  'afghanistan': `https://yesim.app/country/afghanistan/${YESIM_BASE_PARAMS}`,
  'albania': `https://yesim.app/country/albania/${YESIM_BASE_PARAMS}`,
  'algeria': `https://yesim.app/country/algeria/${YESIM_BASE_PARAMS}`,
  'andorra': `https://yesim.app/country/andorra/${YESIM_BASE_PARAMS}`,
  'angola': `https://yesim.app/country/angola/${YESIM_BASE_PARAMS}`,
  'anguilla': `https://yesim.app/country/anguilla/${YESIM_BASE_PARAMS}`,
  'antigua e barbuda': `https://yesim.app/country/antigua-and-barbuda/${YESIM_BASE_PARAMS}`,
  'antigua and barbuda': `https://yesim.app/country/antigua-and-barbuda/${YESIM_BASE_PARAMS}`,
  'arabia saudita': `https://yesim.app/country/saudi-arabia/${YESIM_BASE_PARAMS}`,
  'saudi arabia': `https://yesim.app/country/saudi-arabia/${YESIM_BASE_PARAMS}`,
  'argentina': `https://yesim.app/country/argentina/${YESIM_BASE_PARAMS}`,
  'armenia': `https://yesim.app/country/armenia/${YESIM_BASE_PARAMS}`,
  'aruba': `https://yesim.app/country/aruba/${YESIM_BASE_PARAMS}`,
  'australia': `https://yesim.app/country/australia/${YESIM_BASE_PARAMS}`,
  'austria': `https://yesim.app/country/austria/${YESIM_BASE_PARAMS}`,
  'azerbaigian': `https://yesim.app/country/azerbaijan/${YESIM_BASE_PARAMS}`,
  'azerbaijan': `https://yesim.app/country/azerbaijan/${YESIM_BASE_PARAMS}`,
  'bahamas': `https://yesim.app/country/bahamas/${YESIM_BASE_PARAMS}`,
  'bahrain': `https://yesim.app/country/bahrain/${YESIM_BASE_PARAMS}`,
  'bangladesh': `https://yesim.app/country/bangladesh/${YESIM_BASE_PARAMS}`,
  'barbados': `https://yesim.app/country/barbados/${YESIM_BASE_PARAMS}`,
  'belgio': `https://yesim.app/country/belgium/${YESIM_BASE_PARAMS}`,
  'belgium': `https://yesim.app/country/belgium/${YESIM_BASE_PARAMS}`,
  'belize': `https://yesim.app/country/belize/${YESIM_BASE_PARAMS}`,
  'benin': `https://yesim.app/country/benin/${YESIM_BASE_PARAMS}`,
  'bermuda': `https://yesim.app/country/bermuda/${YESIM_BASE_PARAMS}`,
  'bhutan': `https://yesim.app/country/bhutan/${YESIM_BASE_PARAMS}`,
  'bielorussia': `https://yesim.app/country/belarus/${YESIM_BASE_PARAMS}`,
  'belarus': `https://yesim.app/country/belarus/${YESIM_BASE_PARAMS}`,
  'bolivia': `https://yesim.app/country/bolivia/${YESIM_BASE_PARAMS}`,
  'bosnia ed erzegovina': `https://yesim.app/country/bosnia-and-herzegovina/${YESIM_BASE_PARAMS}`,
  'bosnia and herzegovina': `https://yesim.app/country/bosnia-and-herzegovina/${YESIM_BASE_PARAMS}`,
  'botswana': `https://yesim.app/country/botswana/${YESIM_BASE_PARAMS}`,
  'brasile': `https://yesim.app/country/brazil/${YESIM_BASE_PARAMS}`,
  'brazil': `https://yesim.app/country/brazil/${YESIM_BASE_PARAMS}`,
  'brunei': `https://yesim.app/country/brunei/${YESIM_BASE_PARAMS}`,
  'bulgaria': `https://yesim.app/country/bulgaria/${YESIM_BASE_PARAMS}`,
  'burkina faso': `https://yesim.app/country/burkina-faso/${YESIM_BASE_PARAMS}`,
  'burundi': `https://yesim.app/country/burundi/${YESIM_BASE_PARAMS}`,
  'cambogia': `https://yesim.app/country/cambodia/${YESIM_BASE_PARAMS}`,
  'cambodia': `https://yesim.app/country/cambodia/${YESIM_BASE_PARAMS}`,
  'camerun': `https://yesim.app/country/cameroon/${YESIM_BASE_PARAMS}`,
  'cameroon': `https://yesim.app/country/cameroon/${YESIM_BASE_PARAMS}`,
  'canada': `https://yesim.app/country/canada/${YESIM_BASE_PARAMS}`,
  'capo verde': `https://yesim.app/country/cape-verde/${YESIM_BASE_PARAMS}`,
  'cape verde': `https://yesim.app/country/cape-verde/${YESIM_BASE_PARAMS}`,
  'repubblica ceca': `https://yesim.app/country/czech-republic/${YESIM_BASE_PARAMS}`,
  'czech republic': `https://yesim.app/country/czech-republic/${YESIM_BASE_PARAMS}`,
  'ciad': `https://yesim.app/country/chad/${YESIM_BASE_PARAMS}`,
  'chad': `https://yesim.app/country/chad/${YESIM_BASE_PARAMS}`,
  'cile': `https://yesim.app/country/chile/${YESIM_BASE_PARAMS}`,
  'chile': `https://yesim.app/country/chile/${YESIM_BASE_PARAMS}`,
  'cina': `https://yesim.app/country/china/${YESIM_BASE_PARAMS}`,
  'china': `https://yesim.app/country/china/${YESIM_BASE_PARAMS}`,
  'hong kong': `https://yesim.app/country/hong-kong/${YESIM_BASE_PARAMS}`,
  'hong kong sar china': `https://yesim.app/country/hong-kong/${YESIM_BASE_PARAMS}`,
  'cipro': `https://yesim.app/country/cyprus/${YESIM_BASE_PARAMS}`,
  'cyprus': `https://yesim.app/country/cyprus/${YESIM_BASE_PARAMS}`,
  'città del vaticano': `https://yesim.app/country/vatican-city/${YESIM_BASE_PARAMS}`,
  'vatican city': `https://yesim.app/country/vatican-city/${YESIM_BASE_PARAMS}`,
  'colombia': `https://yesim.app/country/colombia/${YESIM_BASE_PARAMS}`,
  'comore': `https://yesim.app/country/comoros/${YESIM_BASE_PARAMS}`,
  'comoros': `https://yesim.app/country/comoros/${YESIM_BASE_PARAMS}`,
  'congo - brazzaville': `https://yesim.app/country/congo/${YESIM_BASE_PARAMS}`,
  'congo - kinshasa': `https://yesim.app/country/democratic-republic-of-the-congo/${YESIM_BASE_PARAMS}`,
  'corea del sud': `https://yesim.app/country/south-korea/${YESIM_BASE_PARAMS}`,
  'south korea': `https://yesim.app/country/south-korea/${YESIM_BASE_PARAMS}`,
  'costa rica': `https://yesim.app/country/costa-rica/${YESIM_BASE_PARAMS}`,
  'costa d\'avorio': `https://yesim.app/country/cote-d-ivoire/${YESIM_BASE_PARAMS}`,
  'ivory coast': `https://yesim.app/country/cote-d-ivoire/${YESIM_BASE_PARAMS}`,
  'croazia': `https://yesim.app/country/croatia/${YESIM_BASE_PARAMS}`,
  'croatia': `https://yesim.app/country/croatia/${YESIM_BASE_PARAMS}`,
  'cuba': `https://yesim.app/country/cuba/${YESIM_BASE_PARAMS}`,
  'curaçao': `https://yesim.app/country/curacao/${YESIM_BASE_PARAMS}`,
  'curacao': `https://yesim.app/country/curacao/${YESIM_BASE_PARAMS}`,
  'danimarca': `https://yesim.app/country/denmark/${YESIM_BASE_PARAMS}`,
  'denmark': `https://yesim.app/country/denmark/${YESIM_BASE_PARAMS}`,
  'dominica': `https://yesim.app/country/dominica/${YESIM_BASE_PARAMS}`,
  'ecuador': `https://yesim.app/country/ecuador/${YESIM_BASE_PARAMS}`,
  'egitto': `https://yesim.app/country/egypt/${YESIM_BASE_PARAMS}`,
  'egypt': `https://yesim.app/country/egypt/${YESIM_BASE_PARAMS}`,
  'el salvador': `https://yesim.app/country/el-salvador/${YESIM_BASE_PARAMS}`,
  'emirati arabi uniti': `https://yesim.app/country/united-arab-emirates/${YESIM_BASE_PARAMS}`,
  'united arab emirates': `https://yesim.app/country/united-arab-emirates/${YESIM_BASE_PARAMS}`,
  'estonia': `https://yesim.app/country/estonia/${YESIM_BASE_PARAMS}`,
  'etiopia': `https://yesim.app/country/ethiopia/${YESIM_BASE_PARAMS}`,
  'ethiopia': `https://yesim.app/country/ethiopia/${YESIM_BASE_PARAMS}`,
  'figi': `https://yesim.app/country/fiji/${YESIM_BASE_PARAMS}`,
  'fiji': `https://yesim.app/country/fiji/${YESIM_BASE_PARAMS}`,
  'filippine': `https://yesim.app/country/philippines/${YESIM_BASE_PARAMS}`,
  'philippines': `https://yesim.app/country/philippines/${YESIM_BASE_PARAMS}`,
  'finlandia': `https://yesim.app/country/finland/${YESIM_BASE_PARAMS}`,
  'finland': `https://yesim.app/country/finland/${YESIM_BASE_PARAMS}`,
  'francia': `https://yesim.app/country/france/${YESIM_BASE_PARAMS}`,
  'france': `https://yesim.app/country/france/${YESIM_BASE_PARAMS}`,
  'gabon': `https://yesim.app/country/gabon/${YESIM_BASE_PARAMS}`,
  'gambia': `https://yesim.app/country/gambia/${YESIM_BASE_PARAMS}`,
  'georgia': `https://yesim.app/country/georgia/${YESIM_BASE_PARAMS}`,
  'germania': `https://yesim.app/country/germany/${YESIM_BASE_PARAMS}`,
  'germany': `https://yesim.app/country/germany/${YESIM_BASE_PARAMS}`,
  'ghana': `https://yesim.app/country/ghana/${YESIM_BASE_PARAMS}`,
  'giamaica': `https://yesim.app/country/jamaica/${YESIM_BASE_PARAMS}`,
  'jamaica': `https://yesim.app/country/jamaica/${YESIM_BASE_PARAMS}`,
  'giappone': `https://yesim.app/country/japan/${YESIM_BASE_PARAMS}`,
  'japan': `https://yesim.app/country/japan/${YESIM_BASE_PARAMS}`,
  'gibilterra': `https://yesim.app/country/gibraltar/${YESIM_BASE_PARAMS}`,
  'gibraltar': `https://yesim.app/country/gibraltar/${YESIM_BASE_PARAMS}`,
  'giordania': `https://yesim.app/country/jordan/${YESIM_BASE_PARAMS}`,
  'jordan': `https://yesim.app/country/jordan/${YESIM_BASE_PARAMS}`,
  'grenada': `https://yesim.app/country/grenada/${YESIM_BASE_PARAMS}`,
  'grecia': `https://yesim.app/country/greece/${YESIM_BASE_PARAMS}`,
  'greece': `https://yesim.app/country/greece/${YESIM_BASE_PARAMS}`,
  'groenlandia': `https://yesim.app/country/greenland/${YESIM_BASE_PARAMS}`,
  'greenland': `https://yesim.app/country/greenland/${YESIM_BASE_PARAMS}`,
  'guadalupa': `https://yesim.app/country/guadeloupe/${YESIM_BASE_PARAMS}`,
  'guadeloupe': `https://yesim.app/country/guadeloupe/${YESIM_BASE_PARAMS}`,
  'guam': `https://yesim.app/country/guam/${YESIM_BASE_PARAMS}`,
  'guatemala': `https://yesim.app/country/guatemala/${YESIM_BASE_PARAMS}`,
  'guernsey': `https://yesim.app/country/guernsey/${YESIM_BASE_PARAMS}`,
  'guyana francese': `https://yesim.app/country/french-guiana/${YESIM_BASE_PARAMS}`,
  'french guiana': `https://yesim.app/country/french-guiana/${YESIM_BASE_PARAMS}`,
  'guinea': `https://yesim.app/country/guinea/${YESIM_BASE_PARAMS}`,
  'guinea-bissau': `https://yesim.app/country/guinea-bissau/${YESIM_BASE_PARAMS}`,
  'guyana': `https://yesim.app/country/guyana/${YESIM_BASE_PARAMS}`,
  'haiti': `https://yesim.app/country/haiti/${YESIM_BASE_PARAMS}`,
  'honduras': `https://yesim.app/country/honduras/${YESIM_BASE_PARAMS}`,
  'india': `https://yesim.app/country/india/${YESIM_BASE_PARAMS}`,
  'indonesia': `https://yesim.app/country/indonesia/${YESIM_BASE_PARAMS}`,
  'iran': `https://yesim.app/country/iran/${YESIM_BASE_PARAMS}`,
  'iraq': `https://yesim.app/country/iraq/${YESIM_BASE_PARAMS}`,
  'irlanda': `https://yesim.app/country/ireland/${YESIM_BASE_PARAMS}`,
  'ireland': `https://yesim.app/country/ireland/${YESIM_BASE_PARAMS}`,
  'islanda': `https://yesim.app/country/iceland/${YESIM_BASE_PARAMS}`,
  'iceland': `https://yesim.app/country/iceland/${YESIM_BASE_PARAMS}`,
  'isola di man': `https://yesim.app/country/isle-of-man/${YESIM_BASE_PARAMS}`,
  'isle of man': `https://yesim.app/country/isle-of-man/${YESIM_BASE_PARAMS}`,
  'isole cayman': `https://yesim.app/country/cayman-islands/${YESIM_BASE_PARAMS}`,
  'cayman islands': `https://yesim.app/country/cayman-islands/${YESIM_BASE_PARAMS}`,
  'isole faroe': `https://yesim.app/country/faroe-islands/${YESIM_BASE_PARAMS}`,
  'faroe islands': `https://yesim.app/country/faroe-islands/${YESIM_BASE_PARAMS}`,
  'isole salomone': `https://yesim.app/country/solomon-islands/${YESIM_BASE_PARAMS}`,
  'solomon islands': `https://yesim.app/country/solomon-islands/${YESIM_BASE_PARAMS}`,
  'isole turks e caicos': `https://yesim.app/country/turks-and-caicos-islands/${YESIM_BASE_PARAMS}`,
  'turks and caicos islands': `https://yesim.app/country/turks-and-caicos-islands/${YESIM_BASE_PARAMS}`,
  'isole vergini britanniche': `https://yesim.app/country/british-virgin-islands/${YESIM_BASE_PARAMS}`,
  'british virgin islands': `https://yesim.app/country/british-virgin-islands/${YESIM_BASE_PARAMS}`,
  'isole vergini americane': `https://yesim.app/country/us-virgin-islands/${YESIM_BASE_PARAMS}`,
  'us virgin islands': `https://yesim.app/country/us-virgin-islands/${YESIM_BASE_PARAMS}`,
  'israele': `https://yesim.app/country/israel/${YESIM_BASE_PARAMS}`,
  'israel': `https://yesim.app/country/israel/${YESIM_BASE_PARAMS}`,
  'italia': `https://yesim.app/country/italy/${YESIM_BASE_PARAMS}`,
  'italy': `https://yesim.app/country/italy/${YESIM_BASE_PARAMS}`,
  'kazakistan': `https://yesim.app/country/kazakhstan/${YESIM_BASE_PARAMS}`,
  'kazakhstan': `https://yesim.app/country/kazakhstan/${YESIM_BASE_PARAMS}`,
  'kenya': `https://yesim.app/country/kenya/${YESIM_BASE_PARAMS}`,
  'kirghizistan': `https://yesim.app/country/kyrgyzstan/${YESIM_BASE_PARAMS}`,
  'kyrgyzstan': `https://yesim.app/country/kyrgyzstan/${YESIM_BASE_PARAMS}`,
  'kiribati': `https://yesim.app/country/kiribati/${YESIM_BASE_PARAMS}`,
  'kosovo': `https://yesim.app/country/kosovo/${YESIM_BASE_PARAMS}`,
  'kuwait': `https://yesim.app/country/kuwait/${YESIM_BASE_PARAMS}`,
  'laos': `https://yesim.app/country/laos/${YESIM_BASE_PARAMS}`,
  'lesotho': `https://yesim.app/country/lesotho/${YESIM_BASE_PARAMS}`,
  'lettonia': `https://yesim.app/country/latvia/${YESIM_BASE_PARAMS}`,
  'latvia': `https://yesim.app/country/latvia/${YESIM_BASE_PARAMS}`,
  'liberia': `https://yesim.app/country/liberia/${YESIM_BASE_PARAMS}`,
  'liechtenstein': `https://yesim.app/country/liechtenstein/${YESIM_BASE_PARAMS}`,
  'lituania': `https://yesim.app/country/lithuania/${YESIM_BASE_PARAMS}`,
  'lithuania': `https://yesim.app/country/lithuania/${YESIM_BASE_PARAMS}`,
  'lussemburgo': `https://yesim.app/country/luxembourg/${YESIM_BASE_PARAMS}`,
  'luxembourg': `https://yesim.app/country/luxembourg/${YESIM_BASE_PARAMS}`,
  'macedonia del nord': `https://yesim.app/country/north-macedonia/${YESIM_BASE_PARAMS}`,
  'north macedonia': `https://yesim.app/country/north-macedonia/${YESIM_BASE_PARAMS}`,
  'madagascar': `https://yesim.app/country/madagascar/${YESIM_BASE_PARAMS}`,
  'malawi': `https://yesim.app/country/malawi/${YESIM_BASE_PARAMS}`,
  'malesia': `https://yesim.app/country/malaysia/${YESIM_BASE_PARAMS}`,
  'malaysia': `https://yesim.app/country/malaysia/${YESIM_BASE_PARAMS}`,
  'maldive': `https://yesim.app/country/maldives/${YESIM_BASE_PARAMS}`,
  'maldives': `https://yesim.app/country/maldives/${YESIM_BASE_PARAMS}`,
  'mali': `https://yesim.app/country/mali/${YESIM_BASE_PARAMS}`,
  'malta': `https://yesim.app/country/malta/${YESIM_BASE_PARAMS}`,
  'marocco': `https://yesim.app/country/morocco/${YESIM_BASE_PARAMS}`,
  'morocco': `https://yesim.app/country/morocco/${YESIM_BASE_PARAMS}`,
  'martinica': `https://yesim.app/country/martinique/${YESIM_BASE_PARAMS}`,
  'martinique': `https://yesim.app/country/martinique/${YESIM_BASE_PARAMS}`,
  'mauritania': `https://yesim.app/country/mauritania/${YESIM_BASE_PARAMS}`,
  'mauritius': `https://yesim.app/country/mauritius/${YESIM_BASE_PARAMS}`,
  'mayotte': `https://yesim.app/country/mayotte/${YESIM_BASE_PARAMS}`,
  'messico': `https://yesim.app/country/mexico/${YESIM_BASE_PARAMS}`,
  'mexico': `https://yesim.app/country/mexico/${YESIM_BASE_PARAMS}`,
  'moldavia': `https://yesim.app/country/moldova/${YESIM_BASE_PARAMS}`,
  'moldova': `https://yesim.app/country/moldova/${YESIM_BASE_PARAMS}`,
  'monaco': `https://yesim.app/country/monaco/${YESIM_BASE_PARAMS}`,
  'mongolia': `https://yesim.app/country/mongolia/${YESIM_BASE_PARAMS}`,
  'montenegro': `https://yesim.app/country/montenegro/${YESIM_BASE_PARAMS}`,
  'montserrat': `https://yesim.app/country/montserrat/${YESIM_BASE_PARAMS}`,
  'mozambico': `https://yesim.app/country/mozambique/${YESIM_BASE_PARAMS}`,
  'mozambique': `https://yesim.app/country/mozambique/${YESIM_BASE_PARAMS}`,
  'namibia': `https://yesim.app/country/namibia/${YESIM_BASE_PARAMS}`,
  'nauru': `https://yesim.app/country/nauru/${YESIM_BASE_PARAMS}`,
  'nepal': `https://yesim.app/country/nepal/${YESIM_BASE_PARAMS}`,
  'nicaragua': `https://yesim.app/country/nicaragua/${YESIM_BASE_PARAMS}`,
  'niger': `https://yesim.app/country/niger/${YESIM_BASE_PARAMS}`,
  'nigeria': `https://yesim.app/country/nigeria/${YESIM_BASE_PARAMS}`,
  'norvegia': `https://yesim.app/country/norway/${YESIM_BASE_PARAMS}`,
  'norway': `https://yesim.app/country/norway/${YESIM_BASE_PARAMS}`,
  'nuova caledonia': `https://yesim.app/country/new-caledonia/${YESIM_BASE_PARAMS}`,
  'new caledonia': `https://yesim.app/country/new-caledonia/${YESIM_BASE_PARAMS}`,
  'nuova zelanda': `https://yesim.app/country/new-zealand/${YESIM_BASE_PARAMS}`,
  'new zealand': `https://yesim.app/country/new-zealand/${YESIM_BASE_PARAMS}`,
  'paesi bassi': `https://yesim.app/country/netherlands/${YESIM_BASE_PARAMS}`,
  'netherlands': `https://yesim.app/country/netherlands/${YESIM_BASE_PARAMS}`,
  'oman': `https://yesim.app/country/oman/${YESIM_BASE_PARAMS}`,
  'pakistan': `https://yesim.app/country/pakistan/${YESIM_BASE_PARAMS}`,
  'palau': `https://yesim.app/country/palau/${YESIM_BASE_PARAMS}`,
  'panama': `https://yesim.app/country/panama/${YESIM_BASE_PARAMS}`,
  'papua nuova guinea': `https://yesim.app/country/papua-new-guinea/${YESIM_BASE_PARAMS}`,
  'papua new guinea': `https://yesim.app/country/papua-new-guinea/${YESIM_BASE_PARAMS}`,
  'paraguay': `https://yesim.app/country/paraguay/${YESIM_BASE_PARAMS}`,
  'perù': `https://yesim.app/country/peru/${YESIM_BASE_PARAMS}`,
  'peru': `https://yesim.app/country/peru/${YESIM_BASE_PARAMS}`,
  'polinesia francese': `https://yesim.app/country/french-polynesia/${YESIM_BASE_PARAMS}`,
  'french polynesia': `https://yesim.app/country/french-polynesia/${YESIM_BASE_PARAMS}`,
  'polonia': `https://yesim.app/country/poland/${YESIM_BASE_PARAMS}`,
  'poland': `https://yesim.app/country/poland/${YESIM_BASE_PARAMS}`,
  'portogallo': `https://yesim.app/country/portugal/${YESIM_BASE_PARAMS}`,
  'portugal': `https://yesim.app/country/portugal/${YESIM_BASE_PARAMS}`,
  'porto rico': `https://yesim.app/country/puerto-rico/${YESIM_BASE_PARAMS}`,
  'puerto rico': `https://yesim.app/country/puerto-rico/${YESIM_BASE_PARAMS}`,
  'qatar': `https://yesim.app/country/qatar/${YESIM_BASE_PARAMS}`,
  'macao': `https://yesim.app/country/macao/${YESIM_BASE_PARAMS}`,
  'macao sar china': `https://yesim.app/country/macao/${YESIM_BASE_PARAMS}`,
  'regno unito': `https://yesim.app/country/united-kingdom/${YESIM_BASE_PARAMS}`,
  'united kingdom': `https://yesim.app/country/united-kingdom/${YESIM_BASE_PARAMS}`,
  'repubblica centrafricana': `https://yesim.app/country/central-african-republic/${YESIM_BASE_PARAMS}`,
  'central african republic': `https://yesim.app/country/central-african-republic/${YESIM_BASE_PARAMS}`,
  'repubblica dominicana': `https://yesim.app/country/dominican-republic/${YESIM_BASE_PARAMS}`,
  'dominican republic': `https://yesim.app/country/dominican-republic/${YESIM_BASE_PARAMS}`,
  'romania': `https://yesim.app/country/romania/${YESIM_BASE_PARAMS}`,
  'ruanda': `https://yesim.app/country/rwanda/${YESIM_BASE_PARAMS}`,
  'rwanda': `https://yesim.app/country/rwanda/${YESIM_BASE_PARAMS}`,
  'russia': `https://yesim.app/country/russia/${YESIM_BASE_PARAMS}`,
  'saint kitts e nevis': `https://yesim.app/country/saint-kitts-and-nevis/${YESIM_BASE_PARAMS}`,
  'saint kitts and nevis': `https://yesim.app/country/saint-kitts-and-nevis/${YESIM_BASE_PARAMS}`,
  'saint vincent e grenadine': `https://yesim.app/country/saint-vincent-and-the-grenadines/${YESIM_BASE_PARAMS}`,
  'saint vincent and the grenadines': `https://yesim.app/country/saint-vincent-and-the-grenadines/${YESIM_BASE_PARAMS}`,
  'samoa': `https://yesim.app/country/samoa/${YESIM_BASE_PARAMS}`,
  'samoa americane': `https://yesim.app/country/american-samoa/${YESIM_BASE_PARAMS}`,
  'american samoa': `https://yesim.app/country/american-samoa/${YESIM_BASE_PARAMS}`,
  'san marino': `https://yesim.app/country/san-marino/${YESIM_BASE_PARAMS}`,
  'saint martin': `https://yesim.app/country/saint-martin/${YESIM_BASE_PARAMS}`,
  'santa lucia': `https://yesim.app/country/saint-lucia/${YESIM_BASE_PARAMS}`,
  'saint lucia': `https://yesim.app/country/saint-lucia/${YESIM_BASE_PARAMS}`,
  'senegal': `https://yesim.app/country/senegal/${YESIM_BASE_PARAMS}`,
  'serbia': `https://yesim.app/country/serbia/${YESIM_BASE_PARAMS}`,
  'seychelles': `https://yesim.app/country/seychelles/${YESIM_BASE_PARAMS}`,
  'sierra leone': `https://yesim.app/country/sierra-leone/${YESIM_BASE_PARAMS}`,
  'singapore': `https://yesim.app/country/singapore/${YESIM_BASE_PARAMS}`,
  'slovacchia': `https://yesim.app/country/slovakia/${YESIM_BASE_PARAMS}`,
  'slovakia': `https://yesim.app/country/slovakia/${YESIM_BASE_PARAMS}`,
  'slovenia': `https://yesim.app/country/slovenia/${YESIM_BASE_PARAMS}`,
  'spagna': `https://yesim.app/country/spain/${YESIM_BASE_PARAMS}`,
  'spain': `https://yesim.app/country/spain/${YESIM_BASE_PARAMS}`,
  'sri lanka': `https://yesim.app/country/sri-lanka/${YESIM_BASE_PARAMS}`,
  'saint barthélemy': `https://yesim.app/country/saint-barthelemy/${YESIM_BASE_PARAMS}`,
  'stati uniti': `https://yesim.app/country/united-states/${YESIM_BASE_PARAMS}`,
  'united states': `https://yesim.app/country/united-states/${YESIM_BASE_PARAMS}`,
  'sudafrica': `https://yesim.app/country/south-africa/${YESIM_BASE_PARAMS}`,
  'south africa': `https://yesim.app/country/south-africa/${YESIM_BASE_PARAMS}`,
  'sudan': `https://yesim.app/country/sudan/${YESIM_BASE_PARAMS}`,
  'sud sudan': `https://yesim.app/country/south-sudan/${YESIM_BASE_PARAMS}`,
  'south sudan': `https://yesim.app/country/south-sudan/${YESIM_BASE_PARAMS}`,
  'suriname': `https://yesim.app/country/suriname/${YESIM_BASE_PARAMS}`,
  'svezia': `https://yesim.app/country/sweden/${YESIM_BASE_PARAMS}`,
  'sweden': `https://yesim.app/country/sweden/${YESIM_BASE_PARAMS}`,
  'svizzera': `https://yesim.app/country/switzerland/${YESIM_BASE_PARAMS}`,
  'switzerland': `https://yesim.app/country/switzerland/${YESIM_BASE_PARAMS}`,
  'eswatini': `https://yesim.app/country/eswatini/${YESIM_BASE_PARAMS}`,
  'tagikistan': `https://yesim.app/country/tajikistan/${YESIM_BASE_PARAMS}`,
  'tajikistan': `https://yesim.app/country/tajikistan/${YESIM_BASE_PARAMS}`,
  'thailandia': `https://yesim.app/country/thailand/${YESIM_BASE_PARAMS}`,
  'thailand': `https://yesim.app/country/thailand/${YESIM_BASE_PARAMS}`,
  'taiwan': `https://yesim.app/country/taiwan/${YESIM_BASE_PARAMS}`,
  'tanzania': `https://yesim.app/country/tanzania/${YESIM_BASE_PARAMS}`,
  'territori palestinesi': `https://yesim.app/country/palestine/${YESIM_BASE_PARAMS}`,
  'palestinian territories': `https://yesim.app/country/palestine/${YESIM_BASE_PARAMS}`,
  'timor est': `https://yesim.app/country/east-timor/${YESIM_BASE_PARAMS}`,
  'east timor': `https://yesim.app/country/east-timor/${YESIM_BASE_PARAMS}`,
  'tonga': `https://yesim.app/country/tonga/${YESIM_BASE_PARAMS}`,
  'trinidad e tobago': `https://yesim.app/country/trinidad-and-tobago/${YESIM_BASE_PARAMS}`,
  'trinidad and tobago': `https://yesim.app/country/trinidad-and-tobago/${YESIM_BASE_PARAMS}`,
  'tunisia': `https://yesim.app/country/tunisia/${YESIM_BASE_PARAMS}`,
  'turchia': `https://yesim.app/country/turkey/${YESIM_BASE_PARAMS}`,
  'turkey': `https://yesim.app/country/turkey/${YESIM_BASE_PARAMS}`,
  'ucraina': `https://yesim.app/country/ukraine/${YESIM_BASE_PARAMS}`,
  'ukraine': `https://yesim.app/country/ukraine/${YESIM_BASE_PARAMS}`,
  'uganda': `https://yesim.app/country/uganda/${YESIM_BASE_PARAMS}`,
  'ungheria': `https://yesim.app/country/hungary/${YESIM_BASE_PARAMS}`,
  'hungary': `https://yesim.app/country/hungary/${YESIM_BASE_PARAMS}`,
  'uruguay': `https://yesim.app/country/uruguay/${YESIM_BASE_PARAMS}`,
  'uzbekistan': `https://yesim.app/country/uzbekistan/${YESIM_BASE_PARAMS}`,
  'vanuatu': `https://yesim.app/country/vanuatu/${YESIM_BASE_PARAMS}`,
  'venezuela': `https://yesim.app/country/venezuela/${YESIM_BASE_PARAMS}`,
  'vietnam': `https://yesim.app/country/vietnam/${YESIM_BASE_PARAMS}`,
  'yemen': `https://yesim.app/country/yemen/${YESIM_BASE_PARAMS}`,
  'zambia': `https://yesim.app/country/zambia/${YESIM_BASE_PARAMS}`,
  'zimbabwe': `https://yesim.app/country/zimbabwe/${YESIM_BASE_PARAMS}`,
};

// Link generico per Yesim (fallback)
export const YESIM_GENERIC_AFFILIATE = 'https://finanza.me/yesim';

/**
 * Ottiene il link affiliato Yesim specifico per un paese
 * @param country Nome del paese (in italiano o inglese)
 * @returns URL del link affiliato specifico o generico
 */
export function getYesimAffiliateLink(country?: string): string {
  if (!country) {
    return YESIM_GENERIC_AFFILIATE;
  }

  // Normalizza il nome del paese (lowercase e rimuove spazi extra)
  const normalizedCountry = country.toLowerCase().trim();

  // Cerca il link specifico nel mapping
  const specificLink = YESIM_AFFILIATE_MAPPING[normalizedCountry];

  // Restituisce il link specifico se trovato, altrimenti il generico
  return specificLink || YESIM_GENERIC_AFFILIATE;
}

/**
 * Verifica se esiste un link specifico per un paese
 * @param country Nome del paese
 * @returns true se esiste un link specifico, false altrimenti
 */
export function hasSpecificYesimLink(country?: string): boolean {
  if (!country) return false;
  const normalizedCountry = country.toLowerCase().trim();
  return normalizedCountry in YESIM_AFFILIATE_MAPPING;
}
